### ISSUE TITLE
Panning and zooming are a bit unresponsive

### ISSUE THREAD

**Issue by doitandbedone** [doitandbedone/ispyagentdvr-docker#10]
@ispysoftware 
I've noticed that panning and zooming are rather unresponsive/slow, specially if opening from a phone/tablet. I was wondering if this could be improved by perhaps making it more real time, seems it has some sort of delay after you scroll, swipe or pinch. Would be greatly appreciated!

On a side note: Not sure what's the best way to actually open issues/feature requests for the actual software, I don't mind if we continue to use this platform or if you'd like some help to setup something for it. I would recommend Gitlab or similar. Let me know, I'd be happy to help in any way!

**Comment by ispysoftware** [comment]
are you using a ptz camera or is it digital zoom/ pan controls?

**Comment by ispysoftware** [comment]
.. the interface has to send the pan/ zoom command to the server where it does it and returns, if the video from the camera is lagging or buffered on the network then it'll have a delay - should be about the same delay as the actual video is behind real-time (which, depending on encoding can be a few seconds)

**Comment by doitandbedone** [comment]
Thanks for the response! Let me clarify, I meant to zoom and move the video around (after zooming). This is on the active stream without any PTZ involved.

As per PTZ, while I don't own one with zoom, there's a caveat that could be fixed on panning. Once the PTZ controls are enabled, the navigation controls are still active. These get in the way and often exit out to the grid view. If they could be disabled while PTZ is enabled that would be great, at least in single view mode.

**Comment by ispysoftware** [comment]
I removed the swipe to switch views gesture on the latest version - let me know if that helps

**Comment by doitandbedone** [comment]
@ispysoftware Sorry for the delay on the response. Didn't get a chance to post anything before.
Anyhow, update on the zooming and moving. I've recorded a video comparing another software I've used before versus ispy's agent. As you can see the response for the zooms and moving the view around is 1:1, again this is not a PTZ just the regular stream. Wondering if the behavior could be mimicked. Thanks!
See video here:
https://www.dropbox.com/s/90akih9inj1ny3r/ZoomingMovingCameras.mp4?dl=0

**Comment by doitandbedone** [comment]
@ispysoftware As far as PTZ, here's another video on the behavior:
https://www.dropbox.com/s/b5d91i1oekybl33/PTZControls.mp4?dl=0

By the way I'm running ver. 2.8.5.0

**Comment by ispysoftware** [comment]
hmm it's difficult because that example app is doing it on one camera on the client whereas agent is doing it potentially in a grid of cameras. It needs to be done on the server really as the server might be processing a HD stream and the client is only getting a scaled down version of it so to actually get more detail as you zoom in the HD stream needs to be zoomed.

i've fixed a bug with the panning, will do some experiments with faster scale response.

**Comment by doitandbedone** [comment]
So there's actual communication between the client and server for the zoom and movement to happen? Thought it would be some kind of video render which can be literally zoomed as if it was image with no change in stream quality.
Also, if the stream quality is increased to allow this, would this affect performance and amount of concurrent streams?

**Comment by ispysoftware** [comment]
it's actually one video stream coming from agent - the cameras are composited onto a single video stream to save bandwidth (which is how it works over mobile networks with like 20+ cameras). Because PTZ works whilst in grid view you can't zoom/pan a single camera on the client as it will zoom/pan the entire grid of cameras.  I can make the server-side zoom/pan stuff better though.

**Comment by ispysoftware** [comment]
just updating it now, let me know what you think

**Comment by doitandbedone** [comment]
Updated images on docker hub. Already a HUGE improvement, will play around
with it a bit more and will let you know if I find anything.

Thanks for the change!

**Comment by doitandbedone** [comment]
Happy with the changes, closing the issue. Thank you so much!
