### ISSUE TITLE
ONVIF setup fails when using h.265

### ISSUE THREAD

**Issue by DeadEnded** [doitandbedone/ispyagentdvr-docker#109]
**Affected Version**
Agent v3.0.2.0 (running in Docker using doitandbedone/ispyagentdvr:latest)

**Describe the bug**
Trying to add an ONVIF camera generates error.

**Steps To Reproduce**
1. Add Device - ONVIF - click okay to get to general settings
2. Click on three dots beside source type (ONVIF) to get to ONVIF setup
3. Populate username, password, and service URL (http://<IP>/onvif/device)
4. Click Get Video URLs and error appears at the top of screen.

**Expected behavior**
System generates a list of selectable URLs for ONVIF.

**Reproduction rate**
How often does this happen in 100%

**Screenshots**
When attached to the container using `http://<IP>/onvif/device`, the following error appears:
```
Error: ONVIF Device: ONVIF Device: Object reference not set to an instance of an object.
Error: ONVIF Device:    at CoreLogic.Onvif.ONVIFDevice.MediaEndpoint..ctor(MediaUri uri, VideoEncoderConfiguration config)
   at CoreLogic.Onvif.ONVIFDevice.Connect()
Object reference not set to an instance of an object.
Error: Failed to connect
Error:    at CoreLogic.Server.JsonProcessor.LoadJson(Int32 oid, Int32 ot, String lc, String cmd, String data, RTCSession session)
Failed to connect
```

**Host System Information (where ispy agent is running/hosted):**
 - Host OS Ubuntu 20.04.1 LTS
 - running Docker 19.03.12
 - container image with digest # 2ab2b6e16bf0

**Client System Information (device accessing the web portal, if applicable):**
 - OS: Windows 10
 - Browser Chrome
 - Browser Version 87.0.4280.88 (Official Build) (64-bit)

**Additional Information**
Camera supports ONVIF version 19.12(V2.7.0.907196).
Using ONVIF manager, I can connect to the camera using `http://<IP>/onvif/device` so the ONVIF connection does work.
I have successfully setup the camera using the IP camera setup - it is just ONVIF that is not working.

I would like to use ONVIF with the potential to use the camera's detector (this is what I am trying to test).
Please let me know any other information I can gather to help diagnose the issue.

Thank you!
DeadEnd

**Comment by DeadEnded** [comment]
I found the cause... H.265.
My camera has the main stream set to h.265 and the substream to h.264.
Changing my main stream to h.264 fix the issue and ONVIF setup now works.

I can add my camera with h.265 using IP Camera setup, but ONVIF appears to fail on h.265.

**Comment by DeadEnded** [comment]
Little research says that Profile S does not support h.265.
It looks like Profile T was created to support this... not sure what that requires to support if it is not supported already...
Again, h.265 seemed to work (or agentdrv automatically fell back to a sub-stream).

**Comment by ispysoftware** [comment]
hello are you able to port forward the camera and send me a login for debugging it?

**Comment by ispysoftware** [comment]
I added code to the latest update to ignore (not error out on) some missing fields - could you try adding it and let me know if it works now?

**Comment by DeadEnded** [comment]
Yes, that appears to fix the error.
The h264 stream now appears - but it doesn't find the h265.
So that at least lets it not error... just getting the h265 to work now.

I realized this repo is for the docker container... not really the agentdvr software... is there a better place for me to be posting bugs?  I am trying to do testing and want to post any issues I find in the best location for you to track etc.

thanks,
DeadEnd

**Comment by ispysoftware** [comment]
@DeadEnded here is fine. I need to get the profile t onvif implemented for h265

**Comment by DeadEnded** [comment]
ah, okay - if profile T is not implemented that would explain it.
Good to know that you have the root cause.

So if here is fine I will probably post another bug - has to do with changing the storage location... but I'll put details in a new bug.
Been enjoying tinkering with this as currently my NVR is MotionEye with a script to add audio after the recording completes (triggers a parallel process).  If I can get everything figured out the way I want I am fairly confident I will be switching to AgentDVR permanently.

Cheers!
DeadEnd

**Comment by noorbertt** [comment]
I have a same issue, changed the camera to h264 and now its working

**Comment by ispysoftware** [comment]
If someone can send me access to a camera to debug this then I can look into it.

**Comment by ispysoftware** [comment]
I've got an H265 onvif camera working here, seems to be fine feel free to reopen if you still have issues
