### ISSUE TITLE
Error changing storage location (current folder did not exist)

### ISSUE THREAD

**Issue by DeadEnded** [doitandbedone/ispyagentdvr-docker#113]
**Affected Version**
3.0.3.0

**Describe the bug**
Changing the storage location drive AND folder at the same time for a camera causes an error.

**Steps To Reproduce**
1. Go to the storage tab of the setup for a camera
2. Change the drive path to a different drive
3. change the folder name

**Expected behavior**
Storage path changes to new location

**Reproduction rate**
How often does this happen in %100

**Screenshots**
As you can see in the screenshot the error shows the old drive path.
![image](https://user-images.githubusercontent.com/45110141/102548600-e5cbca00-4088-11eb-876b-387cc18936c6.png)

**Host System Information (where ispy agent is running/hosted):**
 - Host OS Ubuntu 20.04.1 LTS
 - running Docker 19.03.12

**Client System Information (device accessing the web portal, if applicable):**
 - OS: Windows 10
 - Browser Chrome
 - Browser Version 87.0.4280.88 (Official Build) (64-bit)

**Additional Information**
To get the issue to resolve, I first change the folder and save. Then I go back and change the drive.  This is a work around, so I expect it has to do with how the system handles changing both fields... After more testing it seems it may be a problem that the original folder wasn't created, and it won't let me change it until it is.  I generated a short recording to cause Agent DVR to create the folder, and then I could change it.

Apologies my testing isn't thorough enough to get all the variables... just playing around with changing the drive and folder to see when I get the error and not I ended up not being able to change the folder at all because the current folder didn't exist.  After saving a recording I could change it.

Cheers!
DeadEnd

**Comment by ispysoftware** [comment]
thanks, have fixed will be in next update

**Comment by DeadEnded** [comment]
Fantastic!
Incredible response time!
I will keep at it and see what else I can find (I am really liking the software and am happy to help squash some bugs :smile: ).
I'm sure I won't find everything, but just playing around with what I can figure out.

Cheers!
DeadEnd

**Comment by ispysoftware** [comment]
should be resolved in 3.0.4.0
