### ISSUE TITLE
Check DeepStack mode/ improve feedback from processing

### ISSUE THREAD

**Issue by danodemano** [doitandbedone/ispyagentdvr-docker#114]
**Affected Version**
v3.0.3.0

**Describe the bug**
Using AI for alerting doesn't block the alert/recording based on filter.

**Steps To Reproduce**
1. Install Deepstack and configure Agent to use it
2. Set up alerts to use "Intelligent Filter"
3. Specify only "people" in the filter
4. Wait for motion - it will alert/record regardless of what it detected in the frame

**Expected behavior**
Recording/Alerting should only happen if the given object is detected in-frame. In this case a person.

**Reproduction rate**
100%

**Screenshots**
![image](https://user-images.githubusercontent.com/1128744/102676938-e1c5a800-416d-11eb-8780-dcddc7c340d0.png)
![image](https://user-images.githubusercontent.com/1128744/102676945-ed18d380-416d-11eb-8685-07d45df16502.png)
![image](https://user-images.githubusercontent.com/1128744/102676956-f7d36880-416d-11eb-8d05-5f80ea55f3b2.png)
![image](https://user-images.githubusercontent.com/1128744/102676964-0588ee00-416e-11eb-9301-bd71c091adff.png)

**Host System Information (where ispy agent is running/hosted):**
Ubuntu 20.04 LTS x64

**Client System Information (device accessing the web portal, if applicable):**
N/A

**Additional Information**
It's possible something isn't configured right, the documentation I found says it's right but I don't know.

**Comment by ispysoftware** [comment]
I'm guessing it can't talk to deepstack for some reason. Check the logs under the server menu

**Comment by danodemano** [comment]
Thanks for the reply! I don't see anything in the logs about it being unable to reach the deepstack server. I attached it though in the event I'm missing something. Deepstack is processing images it appears:

Dec 19 11:13:07 nvr docker[4796]: [GIN] 2020/12/19 - 16:13:07 | 403 |      30.111µs |      172.17.0.1 | POST     /v1/vision/detection
Dec 19 11:13:09 nvr docker[4796]: [GIN] 2020/12/19 - 16:13:09 | 403 |       26.68µs |      172.17.0.1 | POST     /v1/vision/detection
Dec 19 11:13:10 nvr docker[4796]: [GIN] 2020/12/19 - 16:13:10 | 403 |      29.068µs |      172.17.0.1 | POST     /v1/vision/detection
Dec 19 11:13:11 nvr docker[4796]: [GIN] 2020/12/19 - 16:13:11 | 403 |       51.09µs |      172.17.0.1 | POST     /v1/vision/detection
Dec 19 11:13:12 nvr docker[4796]: [GIN] 2020/12/19 - 16:13:12 | 403 |      26.908µs |      172.17.0.1 | POST     /v1/vision/detection
Dec 19 11:13:17 nvr docker[4796]: [GIN] 2020/12/19 - 16:13:17 | 403 |      34.036µs |      172.17.0.1 | POST     /v1/vision/detection
Dec 19 11:13:18 nvr docker[4796]: [GIN] 2020/12/19 - 16:13:18 | 403 |      42.971µs |      172.17.0.1 | POST     /v1/vision/detection
Dec 19 11:13:19 nvr docker[4796]: [GIN] 2020/12/19 - 16:13:19 | 403 |      41.042µs |      172.17.0.1 | POST     /v1/vision/detection
Dec 19 11:13:20 nvr docker[4796]: [GIN] 2020/12/19 - 16:13:20 | 403 |      29.869µs |      172.17.0.1 | POST     /v1/vision/detection
Dec 19 11:13:22 nvr docker[4796]: [GIN] 2020/12/19 - 16:13:22 | 403 |      39.759µs |      172.17.0.1 | POST     /v1/vision/detection

[logs.txt](https://github.com/doitandbedone/ispyagentdvr-docker/files/5719778/logs.txt)

**Comment by ispysoftware** [comment]
hmm i'm not sure - possibly there is something in the frame that deepstack thinks is a person. You could try adjusting the minimum confidence setting up to like 90 or something see if that makes a difference.

**Comment by danodemano** [comment]
Just tried setting it to 100% confidence and same thing. It seems to be ignoring the intelligence filter entirely and just alerting on motion regardless.

**Comment by ispysoftware** [comment]
It's working fine here.. It will ignore the filter if it can't process the response from deepstack but it should give you something in the logs about it but your logs are full of ffmpeg debug. You could try triggering it and then check the logs. If you can port forward your deepstack service I can see what it's returning and if there's an issue there.

**Comment by danodemano** [comment]
So I'm an idiot. I failed to start DeepStack with the

-e VISION-DETECTION=True

Flag. It was running but the right engine wasn't there. Can I change this from a bug report to a feature suggestion? If Deepstack pukes out an error can that be logger? This is the error I got when I tried to manually process an image:

{"success":false,"error":"Detection endpoint not activated"}

Or maybe it did get logged and it was lost in the noise. Sorry for have wasted your time though over my own issue. :D

**Comment by ispysoftware** [comment]
no probs, glad you resolved it - will add some sanity checks to the UI

**Comment by noorbertt** [comment]
Hello,

I have a similar issue, but my deepstack working fine from the start, I use blue iris + aitool
I also can see the is a log in my deepstack docker about the BI and Agent:
(192.168.1.31 is the Agent docker)

What am I missing?
![Screenshot 2020-12-21 at 19 59 43](https://user-images.githubusercontent.com/25225562/102812472-55aebd00-43c7-11eb-8401-7f029e1ea65b.png)
![Screenshot 2020-12-21 at 19 59 08](https://user-images.githubusercontent.com/25225562/102812475-57788080-43c7-11eb-9424-f809c54c421a.png)
![Screenshot 2020-12-21 at 19 57 27](https://user-images.githubusercontent.com/25225562/102812477-59424400-43c7-11eb-8654-1c1f11111459.png)
![Screenshot 2020-12-21 at 20 02 37](https://user-images.githubusercontent.com/25225562/102812586-8abb0f80-43c7-11eb-98f8-93df1438b149.png)

**Comment by ispysoftware** [comment]
You've masked the entire scene so it won't be detecting anything

**Comment by noorbertt** [comment]
Yep, I see now:D

**Comment by ispysoftware** [comment]
resolved in 3.0.4.0
