### ISSUE TITLE
LAN only with yolo?

### ISSUE THREAD

**Issue by noorbertt** [doitandbedone/ispyagentdvr-docker#115]
Hi, 
Can I use this agent dvr with lan only? I dont want to access remotely and I don't want to be accessed.. But also I would like to use yolo. There is a way to do that?

**Comment by ispysoftware** [comment]
Yes you can use this local only. We replaced yolo with deepstack AI.

**Comment by noorbertt** [comment]
oh okay, probably I missed something, but where can I setup a local only?

**Comment by ispysoftware** [comment]
You just set it up and access it via localhost or the ip address of the computer plus the port it's running on

**Comment by doitandbedone** [comment]
Right, if you follow the instructions in the README (main page) that should
set you up. By default everything is local only. You can choose to use
bridge mode by removing the --net=host option in the setup command listed.
