### ISSUE TITLE
Live URL and Record URL issue

### ISSUE THREAD

**Issue by noorbertt** [doitandbedone/ispyagentdvr-docker#119]
Hello,

I try to setup my camera feed
I got a sub 640 x 480 and a main 2560 x 1440 feed and i would like to make a record from the main stream but all I got is the sub live and record.

![Screenshot 2020-12-26 at 20 21 00](https://user-images.githubusercontent.com/25225562/103157895-5032e780-47b8-11eb-8893-29c64a910e3c.png)
My setup shoul be okay, but something wrong.

**Comment by ispysoftware** [comment]
What version of agent are you using? The latest update should have fixed this but a workaround is to set the encoder to auto or none on the recording tab instead of CPU or gpu

**Comment by noorbertt** [comment]
At the moment I have a Agent v3.0.3.0. I changed the encoder from CPU to auto and now its works.
Thank you.
