### ISSUE TITLE
Allow export of core server settings

### ISSUE THREAD

**Issue by danodemano** [doitandbedone/ispyagentdvr-docker#120]
**Describe the solution you'd like**
Would like the ability to backup/export the base server settings in additional to the camera settings. Currently the settings export is only the cameras. Would be useful if migrating to new hardware, re-creating the Docker image, etc. Maybe a tickbox to choose if it's just device settings or all settings? Thanks!

**Comment by ispysoftware** [comment]
will add it in - thanks!

**Comment by ispysoftware** [comment]
this is done, will be in next update - option under the backup/ restore menu.
it won't overwrite some settings, namely userident, uniqueid, machine name and local server port.

**Comment by doitandbedone** [comment]
You could technically do it with Docker. Found some examples here:
https://gist.github.com/thaJeztah/8d0e901bd21329d80cf2

On the other hand, it will be extremely helpful to just export settings as
you may be migrating from docker to a real PC or the other way around.

**Comment by ispysoftware** [comment]
added in latest update

**Comment by doitandbedone** [comment]
Forced for update checks. Merged build should be available in a few minutes.
