### ISSUE TITLE
Ability to set a default view

### ISSUE THREAD

**Issue by danodemano** [doitandbedone/ispyagentdvr-docker#121]
**Is your feature request related to a problem? Please describe.**
Every time I load in the 0 view is default. I want to keep all cameras in this view but have another view that's default.

**Describe the solution you'd like**
I would like to have a specific view set as the default when the interface is loaded up. Maybe I set the view then there is a "default" button? Not sure the proper way to implement to be honest.

**Additional context**
Keep up the great work - loving this software! Still wrapping my brain around it and trying to get remote access working.

**Comment by ispysoftware** [comment]
why not just have 0 as the default and another view with all the cameras in it?

**Comment by danodemano** [comment]
Can you have another view that just has all the cameras automatically if I add/remove them? I was trying to avoid manually maintaining a view since I'm lazy. :D

**Comment by ispysoftware** [comment]
I can add a select/ deselect all checkbox thing into the view manager

**Comment by danodemano** [comment]
That would be perfect actually! Maybe break out the cameras and mics into separate selections or have a select all for each set. Just thinking out loud really.

**Comment by ispysoftware** [comment]
added
