### ISSUE TITLE
Webhook /agent/commands

### ISSUE THREAD

**Issue by noorbertt** [doitandbedone/ispyagentdvr-docker#122]
Hello,

I am try to make a webhook automation when I have a alert.
I managed to create a bat file into: /agent/commands (in this case **talan.bat**)
There is my setup for a alert:
![Screenshot 2020-12-29 at 18 47 45](https://user-images.githubusercontent.com/25225562/103303487-60400680-4a06-11eb-9323-e39a51d29640.png)
When I run a trigger, in this case start recording nothing happen. not sure why?

My log:`
"Entry":"recordingstarted: Bejarat","Type":"Message"},{"Created":"2020-12-29T18:43:07.5485213+01:00","Entry":"Processing EXE (talan.bat)","Type":"Message"},{"Created":"2020-12-29T18:43:07.548913+01:00","Entry":"**No such file or directory**","Type":"Error"},{"Created":"2020-12-29T18:43:07.5489163+01:00","Entry":"Error: No such file or directory","Type":"Message"},{"Created":"2020-12-29T18:43:07.5491756+01:00","Entry":"   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)\n   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)\n   at System.Diagnostics.Process.Start()\n   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)\n   at CoreLogic.Objects.Helpers.AlertProcessor.ProcessAlertEvent(IAgentControl obj, IAgentControl source, String mode, String message, String type, String param1, String param2, String param3, String param4)","Type":"Error"},{"Created":"2020-12-29T18:43:07.5491779+01:00","Entry":"Error:    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)\n   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)\n   at System.Diagnostics.Process.Start()\n   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)\n   at CoreLogic.Objects.Helpers.AlertProcessor.ProcessAlertEvent(IAgentControl obj, IAgentControl source, String mode, String message, String type, String param1, String param2, String param3, String param4)","Type":"Message"},{"Created":"2020-12-29T18:43:07.549182+01:00","Entry":"No such file or directory","Type":"Message"},{"Created":"2020-12-29T18:43:09.6669807+01:00","Entry":"Bejarat: Recording Closed","Type":"Message"},{"Created":"2020-12-29T18:43:15.6808059+01:00","Entry":"rtc:ondatachannelstatechange (download_1609263794747: Open)","Type":"Message"},{"Created":"2020-12-29T18:43:15.680813+01:00","Entry":"rtc: opened download_1609263794747","Type":"Message"}]
`

talan.bat file:

curl -d "" https://mywebhook
If I run a curl -d "" https://mywebhook in Agent DVR docker the webhook works

**Comment by ispysoftware** [comment]
Have you tried including the extension so talan.bat?

**Comment by ispysoftware** [comment]
I think this is because linux can't execute a .bat file - should be a .sh file - but the agent ui will only currently list .bat files. I'll get that fixed up - you could just add a "call url" action instead of using the executable file though

**Comment by ispysoftware** [comment]
ok updated the installer - make sure the file is executable and give it a go

**Comment by noorbertt** [comment]
I have a same error:
`"Entry":"recordingstarted: Bejarat","Type":"Message"},{"Created":"2020-12-30T08:49:13.8807162+01:00","Entry":"Processing EXE (talan.sh)","Type":"Message"},{"Created":"2020-12-30T08:49:13.8811309+01:00","Entry":"No such file or directory","Type":"Error"},{"Created":"2020-12-30T08:49:13.8811323+01:00","Entry":"Error: No such file or directory","Type":"Message"},{"Created":"2020-12-30T08:49:13.8812325+01:00","Entry":"   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)\n   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)\n   at System.Diagnostics.Process.Start()\n   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)\n   at CoreLogic.Objects.Helpers.AlertProcessor.ProcessAlertEvent(IAgentControl obj, IAgentControl source, String mode, String message, String tags, String type, String param1, String param2, String param3, String param4)","Type":"Error"},{"Created":"2020-12-30T08:49:13.8812332+01:00","Entry":"Error:    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)\n   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)\n   at System.Diagnostics.Process.Start()\n   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)\n   at CoreLogic.Objects.Helpers.AlertProcessor.ProcessAlertEvent(IAgentControl obj, IAgentControl source, String mode, String message, String tags, String type, String param1, String param2, String param3, String param4)","Type":"Message"},{"Created":"2020-12-30T08:49:13.8812342+01:00","Entry":"No such file or directory","Type":"Message"},{"Created":"2020-12-30T08:49:53.1103703+01:00","Entry":"rtc:ondatachannelstatechange (download_1609314593652: Open)","Type":"Message"},{"Created":"2020-12-30T08:49:53.110373+01:00","Entry":"rtc: opened download_1609314593652","Type":"Message"}]`

If I use the call url with curl -d '' webhook 
I got this:
`Invalid URI: The URI scheme is not valid."`

Can be the problem a file route?
In the gui agent/commands:
![Screenshot 2020-12-30 at 08 58 25](https://user-images.githubusercontent.com/25225562/103337995-4261b880-4a7d-11eb-9ee1-0d666d226dd9.png)
But in the filesystem agent/Commands:
![Screenshot 2020-12-30 at 08 57 56](https://user-images.githubusercontent.com/25225562/103338012-4c83b700-4a7d-11eb-8d2a-4d7c2b60fb6b.png)

**Comment by ispysoftware** [comment]
ok your issue is that the file you've created isn't executable on linux -
cd to the Commands directory and try running ./talan.sh
take a look at
https://askubuntu.com/questions/229589/how-to-make-a-file-e-g-a-sh-script-executable-so-it-can-be-run-from-a-termi
also, if you are creating the .sh file in windows and copying it in or
modifying one of the existing command files that will also not work as
windows files use different carriage return symbols and linux shell can't
process them - try creating the file in nano instead

https://www.cyberciti.biz/faq/hello-world-bash-shell-script/

**Comment by noorbertt** [comment]
If i type the command ./talan.sh the webhook is working fine.
I created the sh file with nano
nano talan.sh and 
chmod +x talan.sh
and just in case i had a chmod 777 talan.sh

**Comment by noorbertt** [comment]
Ok I tried with the build in options
![Screenshot 2020-12-30 at 12 11 42](https://user-images.githubusercontent.com/25225562/103347772-36cfbb00-4a98-11eb-8097-dc99491c104d.png)
 Entry":"recordingstarted: Bejarat","Type":"Message"},{"Created":"2020-12-30T12:09:11.9132921+01:00","Entry":"Processing EXE (Stop Streaming.bat)","Type":"Message"},{"Created":"2020-12-30T12:09:11.913599+01:00","Entry":"No such file or directory","Type":"Error"},{"Created":"2020-12-30T12:09:11.9136001+01:00","Entry":"Error: No such file or directory","Type":"Message"}

**Comment by ispysoftware** [comment]
I just tried it here with the latest build and it worked fine.. It's running under Linux not Docker but I don't think that would be a problem

**Comment by noorbertt** [comment]
I will try on Linux VM, and will see

**Comment by noorbertt** [comment]
I played with docker and I add a new 
Volume:
/agent/Commands
I got a empty folder but now its working for me.

**Comment by doitandbedone** [comment]
Ah yes, sorry not by my computer. Will be adding this to the instructions
and setup script.

Thanks!

**Comment by doitandbedone** [comment]
Closed #131
