### ISSUE TITLE
I keep getting this message Help wanted

### ISSUE THREAD

**Issue by Spotter2011** [doitandbedone/ispyagentdvr-docker#126]
![Schermafbeelding 2020-12-30 122233](https://user-images.githubusercontent.com/18232630/103348251-c164ea00-4a99-11eb-9137-670e08af5a02.png)
do I have to change something somewhere
I do not understand

**Comment by ispysoftware** [comment]
I think you need to forward your gpu device into the container. I'd use the auto / none encoder personally as that records the raw stream and bypasses the encode step (less CPU)

**Comment by doitandbedone** [comment]
What kind of GPU are you using? Only Nvidia GPUs are not yet fully
supported for the docker image. Thrre is an nvidia tag on github if you
want to experiment with it however.

**Comment by Spotter2011** [comment]
i think this is the problem it is not nvidia thanks for your help this can close
