### ISSUE TITLE
RAM Usage

### ISSUE THREAD

**Issue by Damix48** [doitandbedone/ispyagentdvr-docker#127]
**Affected Version**
v3.0.5.0

**Describe the bug**
Ram usage increase over time by 3/4x

**Steps To Reproduce**
I've a 12 cameras setup (only view, neither recording nor detector) and the RAM usage increase over time by 3/4x (after 3x I restart the container).
The container start using 1.5GB but in about 12 hours it is increased by 3/4x above 5GB sometimes.

**Expected behavior**
Consistent RAM usage 

**Reproduction rate**
How often does this happen in %: 100%

**Screenshots**

**Host System Information (where ispy agent is running/hosted):**
 - OS: Unraid

**Client System Information (device accessing the web portal, if applicable):**
 - OS: Windows 10, Android 10, Ubuntu 20.04 LTS
 - Browser Chrome, Edge, Firefox, Chrome for Android

**Additional Information**
Docker run command `docker run -d --name='ispyagentdvr' --net='proxy-net' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -p '3478:3478/udp' -p '8096:8090/tcp' -v '/mnt/user/appdata/ispyagentdvr/config':'/agent/Media/XML/':'rw' -v '/mnt/user/backup/video/':'/agent/Media/WebServerRoot/Media/':'rw' 'doitandbedone/ispyagentdvr'`

**Comment by doitandbedone** [comment]
12 cameras is a big setup. Are these cameras actively recording and/or
tracking? Do you have events enabled? To me it sounds normal usage if the
cameras are enabled and being used. Does RAM usage keep increasing or
plateaus eventually?

**Comment by Damix48** [comment]
The camera are only in view mode, no record, no tracking. Ram usage keep increasing over time

**Comment by ispysoftware** [comment]
It depends how much memory you have in the system. If you have a lot then there's no pressure to release any. This is only a real issue if it keeps going up and takes your system down. Can you confirm that it does this?

**Comment by Damix48** [comment]
Yes, It's a problem because my supervisor shutdown a VM when the RAM is full. I limited the container to 4GB but it reach the maximum and shutdown the container

**Comment by ispysoftware** [comment]
You'll need to do some debugging. To tux it we need to be able to recreate the issue. It Gould be a specific camera or overloaded computer causing it. Does it happen if you have 1 camera running? 2, 3, 4 etc? Have you checked the logs? How are you connecting to the cameras, what resolution are they, are you buffering video, does stopping and starting the cameras reduce the memory load etc etc

**Comment by ispysoftware** [comment]
I think I found it - looks like a memory leak in the GPU decoder. Have fixed it, running some tests.

**Comment by ispysoftware** [comment]
updated, let me know if it fixes things

**Comment by Damix48** [comment]
Thank you, I will do

**Comment by doitandbedone** [comment]
Buuld should be available in a few minutes

**Comment by Damix48** [comment]
I update, I try it for a few hours.

**Comment by Damix48** [comment]
It seems to work fine

**Comment by doitandbedone** [comment]
Perfect, yhanks for the feedback! Closed #128
