### ISSUE TITLE
Create a build for ARM64

### ISSUE THREAD

**Issue by thewan056** [doitandbedone/ispyagentdvr-docker#134]
**Is your feature request related to a problem? Please describe.**
Doesn't seem to work on AArch64/ARM64? 
I'm trying to run this in docker on my NAS. Its an Asustor 4002t with an Marvell ARMADA-7020 ARM64 CPU.

**Describe the solution you'd like**
Create a build for arm64

**Describe alternatives you've considered**

**Additional context**

**Comment by doitandbedone** [comment]
Will have to pull the base build and test it. I'll take a look.

**Comment by doitandbedone** [comment]
@thewan056 Please use tag arm64 and give it a try.

**Comment by doitandbedone** [comment]
@ispysoftware seems the dependencies for the deb packages are not available for arm, do you recommend any alternatives?

**Comment by ispysoftware** [comment]
Yeah it's not that simple unfortunately. Needs an arm build of webrtc and opencv and ffmpeg. I can possibly do the first 2 but ffmpeg will be the main problem. There's got to be an ffmpeg 4 shared build for arm out there somewhere...

**Comment by doitandbedone** [comment]
Thought so. I started looking for some of then as well. Not that common.
Microsoft does offer a base image fortunately but until we get the
dependencies I'm afraid it won't work.

**Comment by thewan056** [comment]
Noted. Thought I could run lean by purely using my NAS, but I'll be considering getting one of those mini PCs soon. The built in NVR from Asustor is kinda terrible.

**Comment by ispysoftware** [comment]
I've got it working on a raspberry pi 4 - which is Arm 32 bit. Should be able to get a 64 bit build done as well. The FFMPEG snap store build seems to work fine. - 
sudo snap install ffmpeg

**Comment by doitandbedone** [comment]
Giving it a try.

**Comment by doitandbedone** [comment]
Just noticed snap is not available (easily) in a docker image. Since docker images are usually lightweight versions of the actual OS, some things are left out. I did created a build for arm, should build in a few minutes. You can try the tag arm64. Full command:
```
docker run -it -p 8090:8090 -p 3478:3478/udp -p 50000-50010:50000-50010/udp \
-v /appdata/ispyagentdvr/config/:/agent/Media/XML/ \
-v /appdata/ispyagentdvr/media/:/agent/Media/WebServerRoot/Media/ \
-v /appdata/ispyagentdvr/commands:/agent/Commands/ \
--name ispyagentdvr doitandbedone/ispyagentdvr:arm64
```

Do have in mind that it's still missing libjpeg dependency, so not sure what features will be affected exactly but guessing some regarding image captures.

**Comment by ispysoftware** [comment]
I had it running on the Pi on Raspbian OS, dunno what you need to do with Docker to get that. I think it should work on any 32 bit Arm OS although not sure about it.

It will need the arm 32 build, which is here:
https://ispyfiles.azureedge.net/downloads/Agent_ARM32_3_0_8_0.zip
.. and the .net core framework for 32 bit arm which is here:
https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-aspnetcore-3.1.11-linux-arm32-binaries

**Comment by ispysoftware** [comment]
..trying to get it to build opencv for aarch 64 now

**Comment by doitandbedone** [comment]
I would probably recommend to run it directly and bypass Docker as there is some overhead, specially if the system is not on high end hardware. For docker, binaries are the best as it would not support complex things such as snap store. The .NEt is covered by the docker image. FFMPEG (standard) seems to be covered by the vanilla repo but if there's specific libraries needed then we would need to get them. I know you recommend Jonathon's repo which does include some extra stuff.

**Comment by doitandbedone** [comment]
Hmm... Seems dockerhub has an issue when building the image but you can try building the image from source:

1. Download https://github.com/doitandbedone/ispyagentdvr-docker/archive/arm64.zip
2. Unzip content
3. Open command line

```
cd /directory/where/files/are (For example: ~/Downloads/arm64/)
docker build -t  ispy-arm64 .
docker run -it -p 8090:8090 -p 3478:3478/udp -p 50000-50010:50000-50010/udp \
-v /appdata/ispyagentdvr/config/:/agent/Media/XML/ \
-v /appdata/ispyagentdvr/media/:/agent/Media/WebServerRoot/Media/ \
-v /appdata/ispyagentdvr/commands:/agent/Commands/ \
ispy-arm64
```

**Comment by doitandbedone** [comment]
Just changed the download location for ARM specific in the image. Noticed you named it ARM32, is there a 64 bit one? All main RBP are 64bit unless you got a Zero or so, which in this case I would really advise against using it for iSpy :P

**Comment by ispysoftware** [comment]
No not yet, working on it. My pi 4 didn't come with a 64 bit OS and all the
available OS's for it are all 32 bit. You have to hunt down a 64 bit OS for
it and install it manually.

**Comment by thewan056** [comment]
I noticed that Asustors App store, called App Central, has FFmpeg build for my NAS, I wonder if that is usable. 

https://www.asustor.com/app_central/app_detail?id=814&type=18&model=

> Hmm... Seems dockerhub has an issue when building the image but you can try building the image from source:

I tried this and got as far as the 'Connecting Agent'.

**Comment by doitandbedone** [comment]
Hmm, that means it's agent is running, you are still not able to connect? If so, please post your container logs.

**Comment by ispysoftware** [comment]
I uploaded an arm64 build earlier its on the website download page

**Comment by doitandbedone** [comment]
Just added it, thank you! Will be looking on how to automate these as well.

**Comment by jbolanosg** [comment]
I also am interested in a version en ARM64/V8 version...i can help you with test in this platform...I have a Linux server (SBC - TV Box) with amlogic S905x2 processor and operating system ubuntu 20.04

**Comment by jbolanosg** [comment]
i downloaded dockerfile for ARM64 i build the image and i already have Agent DVR running in ARM64...i say you later if i find an error o trouble.
