### ISSUE TITLE
SMTP send throw exceptions

### ISSUE THREAD

**Issue by Vladislav52** [doitandbedone/ispyagentdvr-docker#157]
Affected Version
Agent v3.0.9.0 (running in Docker using doitandbedone/ispyagentdvr:latest)

Describe the bug
SMTP send throw exceptions

Steps To Reproduce

Setup smpt in ispy server settings. Settings is correct. But when message sending (for example alert trigger) i recieve exceptions in log.

Expected behavior
Send email message by SMTP correct.

Reproduction rate
How often does this happen in 100%

Exceptions in log:

{"Created":"2021-01-28T13:24:02.3236542+00:00","Entry":"Error: Mailer: Mailer: The operation has timed out.","Type":"Message"}
,{"Created":"2021-01-28T13:24:02.3252639+00:00","Entry":"Mailer:    at System.Net.Mail.SmtpClient.Send(MailMessage message)\n   at CoreLogic.Mailer.Send(String to, String subject, String body, List`1 attach)","Type":"Error"},{"Created":"2021-01-28T13:24:02.3252704+00:00","Entry":"Error: Mailer:    at System.Net.Mail.SmtpClient.Send(MailMessage message)\n   at CoreLogic.Mailer.Send(String to, String subject, String body, List`1 attach)","Type":"Message"}

Can you help me? :)

Best regards.

**Comment by ispysoftware** [comment]
That just means your smtp server isn't responding

**Comment by Vladislav52** [comment]
I change smtp server from yandex to google and now it works. Thanks. Sorry for my panic :)
