### ISSUE TITLE
Maximum size of folder (MB) settings does not work

### ISSUE THREAD

**Issue by TadasSu** [doitandbedone/ispyagentdvr-docker#163]
Agent v3.1.3.0 (DOCKER)

Maximum size of folder (MB) settings does not work.
I set Max Size to 100 in Main storage settings and in Camera storage settings but media folder grows to 500+ MB and nothing happens.
I expected the old files to be deleted.

**Comment by ispysoftware** [comment]
Do you have storage management enabled and have you checked the logs at logs.html

**Comment by TadasSu** [comment]
Yes, storage management enabled in main settings and in camera settings.
Logs does not show anything about that.
Full log attached from container start, camera enable, record start to record stop:
[log.txt](https://github.com/doitandbedone/ispyagentdvr-docker/files/5942028/log.txt)

**Comment by TadasSu** [comment]
I think I have waited too short for files to be deleted :)
From the logs I see that storage management runs every hour or so. Is that right?
`
10:50:30 AM | Running storage management on /agent/Media/WebServerRoot/Media/
-- | --
10:50:30 AM | Target: 20971520, Current: 26335
10:50:30 AM | Storage monitor: 0 removed 0 failed
11:50:30 AM | Running storage management on /agent/Media/WebServerRoot/Media/
11:50:30 AM | Target: 20971520, Current: 26335
11:50:30 AM | Storage monitor: 0 removed 0 failed
12:50:30 PM | Running storage management on /agent/Media/WebServerRoot/Media/
12:50:30 PM | Target: 20971520, Current: 26335
12:50:30 PM | Storage monitor: 0 removed 0 failed
`

**Comment by ispysoftware** [comment]
Yes that's right.

**Comment by TadasSu** [comment]
Thank you. 
Closing.
