### ISSUE TITLE
Trouble rtsp

### ISSUE THREAD

**Issue by SaymonDzen** [doitandbedone/ispyagentdvr-docker#168]
**Affected Version**
v3.1.3.0

**Describe the bug**
Rstp stream playback does not work.

**Steps To Reproduce**
I connect dvr as ip cams because it is not in the list of devices. Live URL
rtsp: //10.99.20.47:554/user =admin& password=&channel=1&stream=0?.sdp

In the same version of the server, it works fine for Windows.

In VLC 
![image](https://user-images.githubusercontent.com/46021442/108081298-dadde780-7081-11eb-945f-2ea5bc827dc9.png)

**Comment by ispysoftware** [comment]
Logs?

**Comment by SaymonDzen** [comment]
> Logs?

How to enable debug logs for container? Docker logs - clean.

**Comment by doitandbedone** [comment]
They are enabled by default. Depending on your system, the log file may be
limited. Please post more info of your system to help you.

On another note, you can get loga from the ispy sever itself. Go to Server
Menu (top left) and there should be an option to download the log file.
(Not currently by PC, can't remember exact location).

**Comment by ispysoftware** [comment]
just go to /logs.html

**Comment by SaymonDzen** [comment]
12:09:34 | Reconnect: Camera 4 (copy): Reconnecting in 30s
-- | --
12:09:45 | SourceError: Camera 6: CoreLogic.Sources.Combined.VlcStream:Source Error
12:09:45 | Error: SourceError: Camera 6: CoreLogic.Sources.Combined.VlcStream:Source Error
12:09:45 | VLC stopped
12:09:45 | Reconnect: Camera 6: Reconnecting in 10s
12:09:46 | ICE state: Disconnected
12:09:46 | rtc:ondatachannelstatechange (serverdata: Closing)
12:09:46 | rtc:ondatachannelstatechange (serverdata: Closed)
12:09:46 | rtc:ondatachannelstatechange (talk: Closing)
12:09:46 | rtc:ondatachannelstatechange (talk: Closed)

**Comment by SaymonDzen** [comment]
image: doitandbedone/ispyagentdvr:vlc 
host debian 10 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:25 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:38 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by ispysoftware** [comment]
is the stream supposed to be working? I can't connect to it from here using VLC:

Your input can't be opened:
VLC is unable to open the MRL 'rtsp: //10.99.20.47:554/user=admin&password=&channel=1&stream=0?.sdp'. Check the log for details.
Connection failed:
VLC could not connect to "10.99.20.47:554".

**Comment by SaymonDzen** [comment]
10.99.20.47 -  privat IP in LAN :-D
In VLC on Windows working.
![image](https://user-images.githubusercontent.com/46021442/108467000-99258a80-7295-11eb-809e-476ae5b1a1a7.png)

**Comment by SaymonDzen** [comment]
I'm sorry. There were bad firewall settings inside the LAN.
