### ISSUE TITLE
error on rasp pi 2b

### ISSUE THREAD

**Issue by cavedano8** [doitandbedone/ispyagentdvr-docker#176]
Hi,
i've installed on rpi2b the multi-arch docker but i receive this error: standard_init_linux.go:219: exec user process caused: exec format error.
Linux/arm/v7 isn't for rpi2?
Could you help me?
Thanks

**Comment by doitandbedone** [comment]
Multi-arch image is not fully supported just yet that's why there's no
official mention of it. Please use the arm variant. Or install directly
onto the OS.

**Comment by cavedano8** [comment]
Yes, i also try arm variant but i receive "sudo: dotnet: command not found"

**Comment by doitandbedone** [comment]
If you are trying to use it on rbp2 I highly advice against docker. Too
much of an overhead. And I believe we only have the arm64 for docker.
Please install arm/v7 (arm32) directly, follow instructions here:
https://www.ispyconnect.com/download.aspx

**Comment by cavedano8** [comment]
Thanks, but i don't know why, with arm installation there is a problem with dotnet command for me.

**Comment by doitandbedone** [comment]
Could you post the logs? That would give us a better idea.

**Comment by cavedano8** [comment]
For now .. I removed all the programs to try to do a clean install, to see what the problem is. thanks for your support.
In which folder can I see the logs?

**Comment by doitandbedone** [comment]
Should be able to get a print while running the commands on terminal. Did
you follow the guide under ARM (in your case 32bit)?:
https://www.ispyconnect.com/download.aspx

**Comment by ispysoftware** [comment]
You need to install the dotnet core runtime instructions are on the download page

**Comment by leepan8** [comment]
I am trying the install as per https://www.ispyconnect.com/download.aspx for ARM 32 bit. Installation is fine. When adding a device, I am getting an "Illegal instruction" crash.   Using gdb, I had the following output:
---------------------
Thread 82 "dotnet" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x518ff440 (LWP 905)]
0x5996e68c in cv::ThreadPool::run(cv::Range const&, cv::ParallelLoopBody const&, double) ()
   from /home/pi/agent/libcvextern.so
(gdb) bt
#0  0x5996e68c in cv::ThreadPool::run(cv::Range const&, cv::ParallelLoopBody const&, double) ()
    at /home/pi/agent/libcvextern.so
#1  0x5996ae8c in cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double) ()
    at /home/pi/agent/libcvextern.so
#2  0x59bc427c in void cv::resizeGeneric_<cv::HResizeLinear<unsigned char, int, short, 2048, cv::HResizeLinearVecU8_X4>, cv::VResizeLinear<unsigned char, int, short, cv::FixedPtCast<int, unsigned char, 22>, cv::VResizeLinearVec_32s8u> >(cv::Mat const&, cv::Mat&, int const*, void const*, int const*, void const*, int, int, int) () at /home/pi/agent/libcvextern.so
#3  0x59bc8970 in cv::hal::resize(int, unsigned char const*, unsigned int, int, int, unsigned char*, unsigned int, int, int, double, double, int) () at /home/pi/agent/libcvextern.so
#4  0x59bca8a4 in cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int) () at /home/pi/agent/libcvextern.so
#5  0x597cfc94 in cveResize () at /home/pi/agent/libcvextern.so
#6  0x0000038e in  ()
--------------------

**Comment by ispysoftware** [comment]
@leepan8 if you have a new issue then start a new issue. I haven't seen this before but I'd start by checking/ installing all the available dependencies

**Comment by leepan8** [comment]
***

> @leepan8 if you have a new issue then start a new issue. I haven't seen this before but I'd start by checking/ installing all the available dependencies
Ok. I will restart with a clean reinstall and document in a new issue. Thanks.
