### ISSUE TITLE
do you want a smaller image?

### ISSUE THREAD

**Issue by scyto** [doitandbedone/ispyagentdvr-docker#22]
I was playing with the breadcrumb trail you left, nice work.

I am not sure ispy is for me - it has lower quality playback in the browser than my current solution (synology surveillance station). The free unlimited cameras is cool.

II got my image down to about half your size, if you want me to create a pull for edits let me know.
Otherwise i will slink away into the night :-)

![image](https://user-images.githubusercontent.com/11369180/88889342-cd9c0100-d1f4-11ea-963d-4cb20fb46161.png)

**Comment by doitandbedone** [comment]
Go for it and submit a pull. I'll review it.

Thanks!

**Comment by scyto** [comment]
ok, bed time now, will try and do before i go on vacation.

**Comment by scyto** [comment]
PR created https://github.com/doitandbedone/ispyagentdvr-docker/pull/24

**Comment by doitandbedone** [comment]
Thanks, looking at it. Will run and test it later today. Thanks for the
contribution!

**Comment by doitandbedone** [comment]
Changes have been merged into https://github.com/doitandbedone/ispyagentdvr-docker/tree/lite. Will eventually be merged into master.

Thanks @scyto!
