### ISSUE TITLE
docker file can't run on raspberry pi 4

### ISSUE THREAD

**Issue by OmarHeshamACS** [doitandbedone/ispyagentdvr-docker#229]
this version is not working with raspberry pi 4

**Comment by doitandbedone** [comment]
As recommend, you should follow steps for ARM version. Raspberry pi is not
fully supported for docker image.

**Comment by OmarHeshamACS** [comment]
i followed the steps in arm version and it is not working too.

**Comment by doitandbedone** [comment]
Would you mind providing logs please?

**Comment by OmarHeshamACS** [comment]
ok 
[logs for agent dvr on rarspberry pi 4.txt](https://github.com/doitandbedone/ispyagentdvr-docker/files/6585854/logs.for.agent.dvr.on.rarspberry.pi.4.txt)
