### ISSUE TITLE
Does this support hardware acceleration (Intel QuickSync)?

### ISSUE THREAD

**Issue by OscarVanL** [doitandbedone/ispyagentdvr-docker#23]
I've been looking for surveillance software that I can run from within Docker on my Synology 918+ for months. 

So far nothing satisfies this requirement.

I see this uses FFmpeg for encoding, there are some posts where people have been able to get this to work, such as [this one on the Synology forums](https://community.synology.com/enu/forum/17/post/116243), but I don't think it's just an out-of-the-box solution.

Does this or can this utilise hardware acceleration?

**Comment by ispysoftware** [comment]
yeah it will do if the codec is available on the system. You can select quicksync on the recording tab when you edit the camera which will use quicksync to encode or you can select GPU on the decoder when configuring the camera source and that will auto detect any GPU decoders on the system.

Agent can record raw though, which will give you faster encoding than using the GPU to encode.
Also, GPU decoding is often slower than CPU decoding because it can actually take longer to pass the data to the decoder, wait for it to be decoded and then get it back again for further processing.

**Comment by OscarVanL** [comment]
The concern is less about speed/delay and more about CPU Usage. Synology only put crappy Celeron processors in their NASs, so software decoding/encoding is basically out of the question, especially if you want to do motion detection too.

**Comment by MDullak** [comment]
Hi @OscarVanL,
have you completed your quest on getting CPU usage lower?
I just connected 6 cameras (1x1080p and 5x5MP) and I am looking for not paying for Survielance station licenses.
I configured cameras as ONVIF or MJPEG and now I can boil water on the CPU ;-)

Do I need to expose the HW/GPU somehow?

**Comment by OscarVanL** [comment]
Unfortunately no, I tried lots of techniques but eventually just paid for surveillance station.

**Comment by MDullak** [comment]
> Unfortunately no, I tried lots of techniques but eventually just paid for surveillance station.

Thank you for the info.

**Comment by ispysoftware** [comment]
In agent you can motion detect a low res live feed and raw record a high res feed with typically 1-2% cpu

**Comment by MDullak** [comment]
That is my plan for next step. But I am looking on enabling vaapi (if I spelled that correctly as well).
Problem is I have several running projects right now and I was hoping for some quick win.

Maybe changin res will do just that.
Thank you.

**Comment by grinco** [comment]
Not sure about the specific hardware mentioned, but I can confirm that I'm using agentdvr in docker with intel graphics hardware acceleration. Try running docker with --device=/dev/dri:/dev/dri parameter.

intel-gpu-top -  335/ 340 MHz;    0% RC6;  0.69 Watts;      707 irqs/s

      IMC reads:     3496 MiB/s
     IMC writes:     2357 MiB/s

          ENGINE      BUSY                                                 MI_SEMA MI_WAIT
     Render/3D/0    5.59% |██▌                                           |      0%      0%
       Blitter/0    0.00% |                                              |      0%      0%
         Video/0   28.89% |█████████████▎                                |      0%      0%
  VideoEnhance/0    0.00% |                                              |      0%      0%

**Comment by MDullak** [comment]
Thanks for info.
I finally bought licenses for Surveillance as well.

**Comment by mima-mima** [comment]
> Not sure about the specific hardware mentioned, but I can confirm that I'm running this agentdvr image in docker with intel graphics hardware acceleration. Try running docker with --device=/dev/dri:/dev/dri parameter.
> 

I'm on a Synology ds620slim which I believe should have the same expanded hardware support, and /dev/dri is present, but I saw no performance improvement with that device arg when starting docker. @grinco what are your camera settings in agentdvr? I have camera and recording both set to auto, and the log stream indicates it continues to use software.

**Comment by grinco** [comment]
I'm running it with the GPU option explicitly set. Not sure if it worked
with auto. One downside though - looks like there is a memory leak and my
container runs out of memory and restarts every ~24h. Haven't done any
troubleshooting though.

**Comment by MateEke** [comment]
Hi @grinco ! Could you please provide your docker run/docker-compose params, the agent dvr version, and the decoder settings? I have passed in the GPU to the container, set the decoder to GPU on my ONVIF camera, but it seems like it's still not utilized. 

It's my docker-compose.yml, the same config works fine with jellyfin:
```
version: '3'
services:
  agentdvr:
    image: doitandbedone/ispyagentdvr
    container_name: agentdvr
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - '/home/ekemate/agentdvr/config:/agent/Media/XML'
      - '/home/ekemate/agentdvr/commands:/agent/Commands'
      - '/mnt/agentdvr:/agent/Media/WebServerRoot/Media'
    devices:
      - /dev/dri:/dev/dri
    labels:
      - com.centurylinklabs.watchtower.enable=true

```

@ispysoftware I also can't see the quicksync option that you mentioned earlier, is this normal? I have an Intel Iris Pro Graphics 5200 in my server.

> yeah it will do if the codec is available on the system. You can select quicksync on the recording tab when you edit the camera which will use quicksync to encode or you can select GPU on the decoder when configuring the camera source and that will auto detect any GPU decoders on the system.

**Comment by grinco** [comment]
Here's how I run the docker container:

docker run -d -p 8090:8090 -p 3478:3478/udp -p 50000-50010:50000-50010/udp \
-v /opt/agent/Media/XML/:/agent/Media/XML/ \
-v /opt/agent/Media/WebServerRoot/Media/:/agent/Media/WebServerRoot/Media/ \
--device=/dev/dri:/dev/dri \
--restart=always \
--name agentdvr doitandbedone/ispyagentdvr

I'm not running it in privileged mode, but I don't think it would do any
harm. Are you able to get hardware acceleration outside of docker? You
might have to install the drivers. I'm running it on ubuntu 20.04. Try
installing i965-va-driver if you still don't have it.

**Comment by MateEke** [comment]
Thank you!

I have recently tried to install it on the host (Ubuntu 20.4) and it doesn't work. It tries to load CUDA:
```
Camera 2: Opening AV_HWDEVICE_TYPE_CUDA
[AVHWDeviceContext @ 0x7fab4c0c21c0] Cannot load libcuda.so.1
[AVHWDeviceContext @ 0x7fab4c0c21c0] Could not dynamically load CUDA
Camera 2: Couldn't create AV_HWDEVICE_TYPE_CUDA decoder. Using CPU instead.
```

i965-va-driver is installed.

**Comment by grinco** [comment]
Do you have an Nvidia card or driver installed?

**Comment by MateEke** [comment]
No, this server never had any GPU other than the integrated.

**Comment by grinco** [comment]
I know that some laptops have both Intel and Nvidia GPU onboard, and one
needed to switch between them. Am wondering why it's trying to load CUDA
instead of VA. Have you installed any CUDA packages? Ffmpeg CUDA or other
libraries?
