### ISSUE TITLE
RTSP camera does not work over UDP

### ISSUE THREAD

**Issue by brainrecall** [doitandbedone/ispyagentdvr-docker#230]
**Affected Version**
3.3.7.0

**Describe the bug**
I have an RTSP camera that works over TCP and UDP from the Windows version of Agent DVR. However, from the docker-version I can only get a successful connection to the same camera over TCP. Do inbound UDP ports have to be manually opened?

**Steps To Reproduce**
1. Create a IP Camera pointed to a RTSP camera
2. Under the connection settings, in the FFMPEG settings, turn off "Prefer TCP" and set the "RTSP Mode" to UDP.
3. Observe a streamed image is never shown.

**Expected behavior**
RTSP over UDP works.

**Reproduction rate**
100%

**Host System Information (where ispy agent is running/hosted):**
 - OS: Ubuntu Server 20.04.1

**Comment by doitandbedone** [comment]
Port may need to be forwarded via docker, just add -p
<host-port>:<container-port>/udp to the run script/command.

Let me know if that works for you.

**Comment by brainrecall** [comment]
Ok, success!
I'm using docker-compose, so I added: `- '55000-55100:55000-55100/udp'`
100 ports is probably excessive, but why not. The trick, then, was to go to the Video Source settings in Agent, and under FFMPEG, add these options:
```
min_port=55000
max_port=55100
```
That got a good connection. UDP is important to me because my cameras give me near double the framerate on UDP compared to TCP. Thanks for the help!

**Comment by doitandbedone** [comment]
Glad it worked! As for the amount of ports. If you do know which ones it is
better to put onoy those ones as port mapping is known to affect container
performance. On the other hand if you don't see a significant hit then it
would be fine.

**Comment by brainrecall** [comment]
Ah, understood. RTSP needs two UDP ports per camera. I should be able to easily drop it to 10 ports. Thanks again!
