### ISSUE TITLE
Wrong time in docker ispyagentdvr-docker

### ISSUE THREAD

**Issue by whyborn77** [doitandbedone/ispyagentdvr-docker#237]
**Affected Version**
v3.4.2.0

**Describe the bug**
There is a problem with the time in the container.I go to the container console and enter "date" gives the time -3 hours from mine. There is also a problem with scheduled tasks.In the container itself, the time is 3 hours, in the web interface, including watermarks, the time displays correctly.

**Steps To Reproduce**
1. Go to 'container console'
2. tipe 'date' 

**Expected behavior**
there is a problem with scheduled tasks. out of sync in time

**Comment by julianwachholz** [comment]
Set the `TZ` environment variable in your docker container to your correct timezone, e.g. `Europe/London`.

**Comment by doitandbedone** [comment]
@whyborn77 As mentioned by @julianwachholz, provide -e TZ=America/Los_Angeles during your run command of config in whatever docker manager you may have.

Here's a database of the codes:
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Will also be adding this in the sample commands.

Full command would look like:
docker run -it -p 8090:8090 -p 3478:3478/udp -p 50000-50010:50000-50010/udp \
-v /appdata/ispyagentdvr/config/:/agent/Media/XML/ \
-v /appdata/ispyagentdvr/media/:/agent/Media/WebServerRoot/Media/ \
-v /appdata/ispyagentdvr/commands:/agent/Commands/ \
-e TZ=America/Los_Angeles \
--name ispyagentdvr doitandbedone/ispyagentdvr
