### ISSUE TITLE
Timelapses cause crash

### ISSUE THREAD

**Issue by doitandbedone** [doitandbedone/ispyagentdvr-docker#26]
@ispysoftware Seems there is an issue with timelapses, docker for mac seems to spit out things a bit better, here's an excerpt:

```
Writer: Mazda Parking: WriteHeader:Invalid argument <-- This is marked as the error , the rest is a warning, but all cameras with timelapses have the same logs.
Error:    at CoreLogic.RealTime.FFmpegBase.Throw(String method, Int32 code)
   at CoreLogic.RealTime.MediaWriter.Open(String filename, Int32 width, Int32 height, AVCodecID videoCodec, Int32 framerate, AVCodecID audioCodec, DateTime firstFrame, Int32 crf)
   at CoreLogic.Objects.Helpers.TimelapseController.OpenTimelapseWriter()
Error:    at CoreLogic.RealTime.FFmpegBase.Throw(String method, Int32 code)
   at CoreLogic.RealTime.MediaWriter.Open(String filename, Int32 width, Int32 height, AVCodecID videoCodec, Int32 framerate, AVCodecID audioCodec, DateTime firstFrame, Int32 crf)
   at CoreLogic.Objects.Helpers.TimelapseController.OpenTimelapseWriter()
```

I've attached more logs for you to see. Once I disabled timelapses on all cameras the crashes stopped.
Let me know if you need anything else.
[logsCrashAgent.txt](https://github.com/doitandbedone/ispyagentdvr-docker/files/5005457/logsCrashAgent.txt)

Thanks!

**Comment by ispysoftware** [comment]
hmm working on windows - i think it's codec related.. will investigate

**Comment by ispysoftware** [comment]
fixed

**Comment by doitandbedone** [comment]
Perfect, thank you! I'll test it later today.

**Comment by doitandbedone** [comment]
Oh yes, would it be possible to know which version issues get fixed on? Be easy to keep track.

Thank you!

**Comment by ispysoftware** [comment]
There's a changelog here: https://www.ispyconnect.com/producthistory.aspx?productid=27

**Comment by doitandbedone** [comment]
I just meant as issues are closed if you could add the version in the
comment. I'll also start putting more info on new ones. I went ahead and
edited the ones opened.
