### ISSUE TITLE
Random crash (May be related to cameras with less reliable connection; Wifi)

### ISSUE THREAD

**Issue by doitandbedone** [doitandbedone/ispyagentdvr-docker#27]
**Affected version:**
2.6.8.0

**Expected behavior:**
Server should run without any issues, if cameras cannot be contacted, it should handle the error gracefully.

**Actual Result:**
Server crashes after a few minutes, 10+ in my experience. Lots of logs about some cameras not being able to connect/be found are printed.

**Additional info:**
@ispysoftware This crash has been bothering me for a while but it's hard to get it from the server as I set it to restart if anything happens and logs aren't as easy to get. Anyhow, this happens randomly and usually takes 10+ mins to happen. I was able to get a clean set of logs from my mac.
I've noticed that some of the wifi cameras aren't as reliable and well... they do disconnect. Seems there's constant timeouts and seems to be the last logs in the container before it stops, not too sure if it has anything to do with it however.
[agentRandomCrash.txt](https://github.com/doitandbedone/ispyagentdvr-docker/files/5005652/agentRandomCrash.txt)

**Steps to reproduce:**
Boot the server
Have one or more wifi cameras added in the network
Check logs for camera connectivity issues.
Using [Amcrest IP3M-HX2W](https://amcrest.com/amcrest-hex-3mp-wifi-video-security-ip-camera-pt-856.html)
Eventually it will timeout with this message:
```
The HTTP request to 'http://<redacted-ip>/onvif/device_service' has exceeded the allotted timeout of 00:00:15. The time allotted to this operation may have been a portion of a longer timeout.
[39;49m[33m[40mError: SourceError: Deck: CoreLogic.Sources.Combined.MediaStream:Invalid Source ()
```

**Comment by doitandbedone** [comment]
After updating to 2.8.7.0 the server has been running consistently for more than 1hr now. Fix for #26 may have fixed this issue as well. I'll let it run for the whole night and check back in the morning.

**Comment by ispysoftware** [comment]
Sorry I didn't see this. Feel free to tag me in.

**Comment by doitandbedone** [comment]
@ispysoftware Server has been running for 12hrs straight with no crash. I'll close this for now, if I find any other problem I'll open a new issue.

Thank you!
