### ISSUE TITLE
Unable to update docker image

### ISSUE THREAD

**Issue by danodemano** [doitandbedone/ispyagentdvr-docker#295]
**Affected Version**
v3.4.3.0

**Describe the bug**
Running "sudo docker pull doitandbedone/ispyagentdvr:latest" doesn't update the image

**Expected behavior**
Command should update the image

**Reproduction rate**
100%

**Screenshots**
![image](https://user-images.githubusercontent.com/1128744/127938661-22e538af-793e-44fa-892b-331d325634c9.png)

**Host System Information (where ispy agent is running/hosted):**
 - OS: Ubuntu 20.04.2 LTS

**Additional Information**
I don't know when this stopped working. As you can see the image is ~4 weeks old. I also tried to use the updating instructions from the readme but that didn't seem to do anything, I'm still running the old version.

**Comment by doitandbedone** [comment]
Hmm, thanks for letting me know. I just found out dockerhub is no longer
offering free automated builds. I'm afraid this will be causing delays. So
far the latest is 3.5.0.0. You may manually build the image at this point.
I'll update it later today or tomorrow. Will post an update when it's done.

**Comment by danodemano** [comment]
Thanks for the quick update and the images! I'm not smart enough to build one myself so I'll just wait, lol.

**Comment by doitandbedone** [comment]
Seems even manual builds have been taken off and pushed to paid plans. I
think I found another way to automate them from github's side but it will
take some time to get it going, so please be patient!

**Comment by doitandbedone** [comment]
Took some trial and error but finally got it working! Latest as of now is 3.5.2.0, so you can now pull the version. At this point however, some older tags (github) did not generate builds, I will have to push builds manually, but that's for another day...

Anyhow, give it a try and let me know if you have any issues!

**Comment by danodemano** [comment]
@doitandbedone - looks like that got it, thanks so much!!!

**Comment by doitandbedone** [comment]
Cool! Glad it got resolved!
