### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by DivanX10** [doitandbedone/ispyagentdvr-docker#303]
Is it possible to add telegram actions to the list so that when the movement is recorded, the pictures are sent to telegram? Now this is done using the Home Assistant. Telegram is now used by many and many connect Telegram to the Home Assistant, to the robot vacuum cleaner, to the router

![image](https://user-images.githubusercontent.com/64090632/131022174-58a483e0-423b-43b2-afd7-5ed09af1b3e4.png)

**Comment by ispysoftware** [comment]
hey just added telegram bot support to the latest update.

**Comment by ispysoftware** [comment]
see the telegram link in the server menu in agent to add the bot

**Comment by ispysoftware** [comment]
https://www.ispyconnect.com/userguide-agent-integrations.aspx#telegram

**Comment by DivanX10** [comment]
Thank you very much. This is very good news
