### ISSUE TITLE
can't load the app

### ISSUE THREAD

**Issue by alexanderzatko** [doitandbedone/ispyagentdvr-docker#305]
I had the image running couple of months ago, but with the latest version - when I try to connect to localhost:8090 - I can't. I am using Mac as the host. Below is the log.

Starting...
Creating temp path for opencv in /tmp/
Get com port list
Discover Onvif
Start network scan
Agent (v3.5.4.0)
Log start
Process is 64 bit 
Init Webrtc
Init FFmpeg
IP addresses:
172.17.0.2
found 172.17.0.1
found 172.17.0.2
H264 compatible version of ffmpeg is required to use H264 encoding. Switch to VP8 in settings if unable to record.
Looking for ffmpeg in /usr/local/lib
Not in there..
Looking for ffmpeg in /usr/lib/x86_64-linux-gnu
ffmpeg path: /usr/lib/x86_64-linux-gnu
Initializing devices
Hardware Decoders:
vdpau
vaapi
drm
opencl
Found 0 devices
call arecord -l
Error: CMD: CMD: No such file or directory
Error: CMD:    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CoreLogic.Utilities.CMD.GetOutput(String exe, String strCommand)
No such file or directory
Error: No audio devices found
Preloading Images
Turn Server accepting connections at 172.17.0.2:3478 using range 50000-50010)
MQTT not configured or enabled
Loaded 0 cameras and 0 mics from /agent/Media/XML/objects.xml
Using default port (8090)
Local Server running on port 8090
Access locally at http://172.17.0.2:8090
Accepting connections at http://*:8090/
ZeroConf: ZeroConf Service Started
Running at http://localhost:8090

**Comment by doitandbedone** [comment]
Make sure you are running the software as network type host in mac. I'm
afraid there's limitations for Docker for mac. Also, go ahead and share the
command you are using to run the container, maybe I can give you some
pointers.

**Comment by alexanderzatko** [comment]
I was starting the image from docker (see attached pic), but for a change I used the command found on the ispyconnect web site and now I can log into the agentdvr.

`docker run -it -p 8090:8090 -p 3478:3478/udp -p 50000-50010:50000-50010/udp --name agentdvr doitandbedone/ispyagentdvr:latest`

Thank you for responding so quickly (and for the image) :-)

<img width="1382" alt="Screenshot 2021-08-28 at 20 28 48" src="https://user-images.githubusercontent.com/3430677/131227570-b1530c0f-dcf6-40aa-9c95-b84e1702fe07.png">

**Comment by doitandbedone** [comment]
Glad that helped. And yes, please follow instructions as posted for best
results!

**Comment by anionDev** [comment]
I get the same error on a Windows host. 
I tried 
- `docker run -it -p 8090:8090 -p 3478:3478/udp -p 50000-50010:50000-50010/udp --name agentdvr doitandbedone/ispyagentdvr:latest`
- `docker run -it -p 8090:8090 -p 3478:3478/udp -p 50000-50010:50000-50010/udp --name agentdvr --network host doitandbedone/ispyagentdvr:latest`

are there any ideas how to solve/debug the problem?

**Comment by doitandbedone** [comment]
Please share your logs.

**Comment by anionDev** [comment]
<details>
  <summary>i got this output</summary>
  
```
>docker run -it -p 8090:8090 -p 3478:3478/udp -p 50000-50010:50000-50010/udp --name agentdvr doitandbedone/ispyagentdvr:latest
Starting...
Creating temp path for opencv in /tmp/
Get com port list
Discover Onvif
Start network scan
Agent (v3.5.4.0)
Log start
Process is 64 bit
Init Webrtc
Init FFmpeg
IP addresses:
172.17.0.2
found 172.17.0.1
found 172.17.0.2
H264 compatible version of ffmpeg is required to use H264 encoding. Switch to VP8 in settings if unable to record.
Looking for ffmpeg in /usr/local/lib
Not in there..
Looking for ffmpeg in /usr/lib/x86_64-linux-gnu
ffmpeg path: /usr/lib/x86_64-linux-gnu
Initializing devices
Hardware Decoders:
vdpau
vaapi
drm
opencl
Found 0 devices
call arecord -l
Error: CMD: CMD: No such file or directory
Error: CMD:    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CoreLogic.Utilities.CMD.GetOutput(String exe, String strCommand)
No such file or directory
Error: No audio devices found
Preloading Images
Turn Server accepting connections at 172.17.0.2:3478 using range 50000-50010)
MQTT not configured or enabled
Loaded 0 cameras and 0 mics from /agent/Media/XML/objects.xml
Using default port (8090)
Local Server running on port 8090
Access locally at http://172.17.0.2:8090
Accepting connections at http://*:8090/
ZeroConf: ZeroConf Service Started
Running at http://localhost:8090
```
as far as i know there are no other log-files which i could post here.
</details>

as far as i know there are no other log-files which i could post here.
i do not know whether it does matter but maybe it is worth to mention:
- i am using windows server 2019 with all available updates installed.
- in windows settings i allowed that apps are able to use the microphone. (when i started the container i got a notification using the microphone by apps is not allowed by apps so i allowed it and restarted the container with the same result.)
- there is no physical audio-input-device available on the server (only a virtual one).
- there is no physical audio-output-device available on the server (only a virtual one).
- the server uses the onboard-graphics-chip for the screen, there is no "real" videocard available.

**Comment by doitandbedone** [comment]
What happens when you acces your server's IP via port 8090?

**Comment by anionDev** [comment]
When there is a `No such file or directory` when starting a process then i guess the executable-file/workingdirectory/something like this is not available. but the container does not entirely break. it is still running. so i can `docker exec` into the container. (i can also "access" the webui but it says "Connecting". so it seems that i can only access the webserver which does not have a connection to any other required service.)

<details>
  <summary>in the container i have this files in the agent-folder</summary>

```
root@fcd29e100bf5:/agent# ls -la
total 69380
drwxr-xr-x 1 root root     4096 Sep 16 21:20 .
drwxr-xr-x 1 root root     4096 Sep 16 21:20 ..
-rw-r--r-- 1 root root    89632 Aug 20 16:19 Agent
-rw-r--r-- 1 root root    92674 Aug 20 16:19 Agent.deps.json
-rw-r--r-- 1 root root   194048 Aug 20 16:19 Agent.dll
-rw-r--r-- 1 root root     2292 Aug  4 16:42 Agent.dll.config
-rw-r--r-- 1 root root      235 Aug 20 16:19 Agent.runtimeconfig.json
-rw-r--r-- 1 root root     1187 Aug  4 16:42 AgentDVR.service
drwxr-xr-x 2 root root     4096 Sep 16 21:20 Commands
-rw-r--r-- 1 root root    10240 Aug 16  2017 Common.Logging.Core.dll
-rw-r--r-- 1 root root    39424 Aug 16  2017 Common.Logging.dll
-rw-r--r-- 1 root root  8829952 Aug 20 16:19 CoreLogic.dll
-rw-r--r-- 1 root root     9216 Aug 20 16:19 CoreUpdater.dll
-rw-r--r-- 1 root root      154 Aug 20 16:19 CoreUpdater.runtimeconfig.json
-rw-r--r-- 1 root root   303104 Aug  4 16:42 DirectShowLib-2005.dll
-rw-r--r-- 1 root root   715776 Aug 16 08:53 Emgu.CV.Platform.NetStandard.dll
-rw-r--r-- 1 root root   786944 Apr 10 15:10 FFmpeg.AutoGen.dll
-rw-r--r-- 1 root root     5120 Aug  9 18:03 Google.Apis.Auth.PlatformServices.dll
-rw-r--r-- 1 root root   161792 Aug  9 18:03 Google.Apis.Auth.dll
-rw-r--r-- 1 root root    77312 Aug  9 18:03 Google.Apis.Core.dll
-rw-r--r-- 1 root root   134656 Aug  9 18:18 Google.Apis.Drive.v3.dll
-rw-r--r-- 1 root root    80896 Aug  9 18:03 Google.Apis.dll
-rw-r--r-- 1 root root   195072 Feb  2  2021 KoenZomers.OneDrive.Api.dll
-rw-r--r-- 1 root root   227328 Jun  8 16:38 LibVLCSharp.dll
-rw-r--r-- 1 root root    61440 Jan 21  2021 LitJSON.dll
-rw-r--r-- 1 root root   295936 Jun 29 02:43 MQTTnet.dll
-rw-r--r-- 1 root root    34304 Nov  5  2019 Makaretu.Dns.Multicast.dll
-rw-r--r-- 1 root root    91648 Jul 23  2019 Makaretu.Dns.dll
drwxr-xr-x 2 root root     4096 Aug 20 12:06 Masks
drwxr-xr-x 4 root root     4096 Sep 16 21:20 Media
-rw-r--r-- 1 root root    36232 Jan 21  2021 Microsoft.AspNetCore.Connections.Abstractions.dll
-rw-r--r-- 1 root root    96136 Jan 21  2021 Microsoft.AspNetCore.Http.Connections.Client.dll
-rw-r--r-- 1 root root    27016 Jan 21  2021 Microsoft.AspNetCore.Http.Connections.Common.dll
-rw-r--r-- 1 root root    30592 Jan 21  2021 Microsoft.AspNetCore.Http.Features.dll
-rw-r--r-- 1 root root   144264 Jan 21  2021 Microsoft.AspNetCore.SignalR.Client.Core.dll
-rw-r--r-- 1 root root    18312 Jan 21  2021 Microsoft.AspNetCore.SignalR.Client.dll
-rw-r--r-- 1 root root    37768 Jan 21  2021 Microsoft.AspNetCore.SignalR.Common.dll
-rw-r--r-- 1 root root    33672 Jan 21  2021 Microsoft.AspNetCore.SignalR.Protocols.Json.dll
-rw-r--r-- 1 root root    21384 Jan 20  2021 Microsoft.Extensions.Configuration.Abstractions.dll
-rw-r--r-- 1 root root    25480 Jan 20  2021 Microsoft.Extensions.Configuration.Binder.dll
-rw-r--r-- 1 root root    27520 Jan 20  2021 Microsoft.Extensions.Configuration.dll
-rw-r--r-- 1 root root    37768 Jan 20  2021 Microsoft.Extensions.DependencyInjection.Abstractions.dll
-rw-r--r-- 1 root root    72584 Jan 20  2021 Microsoft.Extensions.DependencyInjection.dll
-rw-r--r-- 1 root root    48520 Jan 20  2021 Microsoft.Extensions.Logging.Abstractions.dll
-rw-r--r-- 1 root root    34184 Jan 20  2021 Microsoft.Extensions.Logging.dll
-rw-r--r-- 1 root root    50568 Jan 20  2021 Microsoft.Extensions.Options.dll
-rw-r--r-- 1 root root    38792 Jan 20  2021 Microsoft.Extensions.Primitives.dll
-rw-r--r-- 1 root root    41352 Oct 20  2020 Microsoft.Win32.Registry.dll
-rw-r--r-- 1 root root    27528 Oct 20  2020 Microsoft.Win32.SystemEvents.dll
-rw-r--r-- 1 root root   510464 Feb  1  2020 NAudio.dll
-rw-r--r-- 1 root root   693680 Nov  9  2019 Newtonsoft.Json.dll
-rw-r--r-- 1 root root    24576 Aug 20 16:19 OnvifDiscovery.dll
-rw-r--r-- 1 root root   801792 Jan 24  2021 Renci.SshNet.dll
-rw-r--r-- 1 root root   111104 Aug 20 16:19 RtspClientSharp.dll
-rw-r--r-- 1 root root    93184 May 16  2020 SQLite-net.dll
-rw-r--r-- 1 root root     6144 May  1  2020 SQLitePCLRaw.batteries_v2.dll
-rw-r--r-- 1 root root    46592 May  1  2020 SQLitePCLRaw.core.dll
-rw-r--r-- 1 root root     5632 May  1  2020 SQLitePCLRaw.nativelibrary.dll
-rw-r--r-- 1 root root    56832 May  1  2020 SQLitePCLRaw.provider.dynamic_cdecl.dll
-rw-r--r-- 1 root root    12800 Jul 27  2017 SimpleBase.dll
-rw-r--r-- 1 root root   414096 Jul 10 06:08 SkiaSharp.dll
-rw-r--r-- 1 root root    34816 Oct 23  2017 SshNet.Security.Cryptography.dll
-rw-r--r-- 1 root root   419728 Feb 17  2021 System.Drawing.Common.dll
-rw-r--r-- 1 root root    65928 Nov 17  2020 System.IO.Pipelines.dll
-rw-r--r-- 1 root root    69520 Feb 17  2021 System.IO.Ports.dll
-rw-r--r-- 1 root root    23552 Feb 15  2018 System.Net.IPNetwork.dll
-rw-r--r-- 1 root root  2560904 Jan 29  2021 System.Private.ServiceModel.dll
-rw-r--r-- 1 root root    35712 Apr 15  2020 System.Reflection.DispatchProxy.dll
-rw-r--r-- 1 root root    54136 Nov 15  2019 System.Resources.Extensions.dll
-rw-r--r-- 1 root root    55688 Oct 20  2020 System.Security.AccessControl.dll
-rw-r--r-- 1 root root   246136 Nov 15  2019 System.Security.Cryptography.Pkcs.dll
-rw-r--r-- 1 root root   160632 Nov 15  2019 System.Security.Cryptography.Xml.dll
-rw-r--r-- 1 root root    92536 Nov 15  2019 System.Security.Permissions.dll
-rw-r--r-- 1 root root    37768 Oct 20  2020 System.Security.Principal.Windows.dll
-rw-r--r-- 1 root root    14208 Jan 29  2021 System.ServiceModel.Duplex.dll
-rw-r--r-- 1 root root    15240 Jan 29  2021 System.ServiceModel.Http.dll
-rw-r--r-- 1 root root    14728 Jan 29  2021 System.ServiceModel.NetTcp.dll
-rw-r--r-- 1 root root    21384 Jan 29  2021 System.ServiceModel.Primitives.dll
-rw-r--r-- 1 root root    16264 Jan 29  2021 System.ServiceModel.Security.dll
-rw-r--r-- 1 root root    23432 Jan 29  2021 System.ServiceModel.dll
-rw-r--r-- 1 root root    49536 Apr 15  2020 System.Threading.Channels.dll
-rw-r--r-- 1 root root    25976 Nov 15  2019 System.Windows.Extensions.dll
-rw-r--r-- 1 root root   108544 Feb 15  2019 Tmds.LibC.dll
drwxr-xr-x 3 root root     4096 Aug 20 12:06 XML
-rw-r--r-- 1 root root       27 Aug  4 16:42 agent-register.sh
-rw-r--r-- 1 root root       36 Aug  4 16:42 agent-reset-local-login.sh
-rw-r--r-- 1 root root       24 Aug  4 16:42 agent-reset.sh
-rw-r--r-- 1 root root  8558128 Jul 10 05:51 libSkiaSharp.so
-rw-r--r-- 1 root root    18568 Feb 17  2021 libSystem.IO.Ports.Native.so
-rw-r--r-- 1 root root 26529616 Aug  4 16:42 libcvextern.so
-rw-r--r-- 1 root root  1142792 Apr  8  2020 libe_sqlite3.so
-rw-r--r-- 1 root root 14295768 Aug  4 16:42 libjingle_peerconnection_so.so
drwxr-xr-x 2 root root     4096 Aug 20 12:06 sounds
-rw-r--r-- 1 root root    68096 Aug 20 16:19 webrtc.dll
```

</details>

(which looks pretty normal for a .NET-application in my opinion.)
are there maybe commandline-ways to get more information about which file or directory is not available?

**Comment by doitandbedone** [comment]
@ispysoftware If you can please take a look into this folder issue. It also is odd that the TURN server is picking up a port outside the range:
`Turn Server accepting connections at 172.17.0.2:3478 using range 50000-50010`
@anionDev Just as a side note, you have no mappings so it will not persist any data. Use the volumes as indicated in the commands if you do want this to work in the future.

**Comment by anionDev** [comment]
I know, I first tried to use volumes. Then I copied alexanderzatko's commands only as minimal-example to reproduce the problem. And this also ensures that the reason for the error is not wrong data in my volumes-folder. :-)

**Comment by doitandbedone** [comment]
Yes, the directory error I'm guessing is a module failure. About the volumes, it was a side note. IT's not necessary for it to run or work, just to persist data on the long run. 
As for the infinite loading it used to happen due to the server not being able to access ports, but that's why TURN ports where introduced. A quick check would be is to see if the mappings are happening and if there's no port collisions by inspecting the image.
Also, I just updated the image to latest version, please update and see if this somehow fixes the issue. Otherwise let's wait for @ispysoftware to reply back.

**Comment by anionDev** [comment]
same behaior

**Comment by ispysoftware** [comment]
sounds like possibly a firewall issue on the host - any reason you are using the docker version and not the native windows version?

**Comment by anionDev** [comment]
> sounds like possibly a firewall issue on the host

i will check that.

> any reason you are using the docker version and not the native windows version?

i generally prefer docker because it app-management using docker is very easy and i can easily re-deploy applications when i have to reinstall the host-os for any reason.

**Comment by anionDev** [comment]
> sounds like possibly a firewall issue on the host

Now i have checked that using the command `docker run -it -p 8090:8090 -p 3478:3478/udp -p 50000-50010:50000-50010/udp --name agentdvr doitandbedone/ispyagentdvr:lates` on 2 devices:
1. On a windows server 2019 with disabled firewall
2. On a usual windows 10 with disabled firewall

I always get the behavior described above.
Can you reproduce this behavior in some way? Does this command start a working ispyagentdvr-instance on your system?

**Comment by doitandbedone** [comment]
@anionDev Please update to 4.1.2.0 and verify and reopen if still have issues.
