### ISSUE TITLE
[Feature Request] Recordings purge

### ISSUE THREAD

**Issue by doitandbedone** [doitandbedone/ispyagentdvr-docker#32]
@ispysoftware I've noticed that I have a bunch of missing files, probably old files from the encoder crashes fixed in #26. Would it be possible to have a way to purge these videos? Doing this manually with the amount fo cameras and recordings seems like a daunting task. A purge button in Recordings edit mode would be great, with a confirmation on how many will be deleted.

See below:
![Corrupt Files](https://user-images.githubusercontent.com/61026996/89348203-ff7fee00-d660-11ea-8a22-0adebbc7ff7d.png)

Thanks!

**Comment by ispysoftware** [comment]
You can click the camera header to select all recordings or draw out a box on desktop to select multiple.
