### ISSUE TITLE
Missing container in docker

### ISSUE THREAD

**Issue by djdoubleg** [doitandbedone/ispyagentdvr-docker#324]
I installed my system (Debian GNU/Linux 8 (jessie)) this container under docker (  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)).
But it disappears from the docker every third day.
Why?

**Affected Version**
doitandbedone/ispyagentdvr:latest(donloaded from github)

**Describe the bug**
After install, the conatiner diaspear several days.

**Steps To Reproduce**
1. install ispyagentdvr under docker
2. run
3. wait three days
4. try to reach the agent web site
5. very slow responding
6. refresh the page
7. missing container (no log, no folder in docker)

**Expected behavior**
Never remove the container

**Reproduction rate**
100%

**Screenshots**

**Host System Information (where ispy agent is running/hosted):**
Debian GNU/Linux 8.11 (jessie)
Linux 4.9.0-0.bpo.6-amd64

**Client System Information (device accessing the web portal, if applicable):**
platform independent

**Additional Information**

**Comment by doitandbedone** [comment]
Closed, more information needed
