### ISSUE TITLE
When enabling FTP, disable writing to local storage

### ISSUE THREAD

**Issue by DivanX10** [doitandbedone/ispyagentdvr-docker#329]
Agent DVR has an FTP function that allows you to save photos and videos to the specified folders, but at the same time photos and videos are also saved to local folders. It turns out that the photo and video files will be in two places and it is not always necessary. Is it possible to add a function so that when FTP is enabled, photos and videos are not saved to local storage. For example, add a switch to the FTP settings, which can be turned on if desired, and then photos and videos will not be saved to local storage

**Comment by ispysoftware** [comment]
It needs to write to local storage so it can read it to upload it. If the FTP server is down it also needs to be able to wait a while to retry. You can use storage management and set the max time to 1 hour if you want but Agent definitely needs somewhere to write the file to.

**Comment by DivanX10** [comment]
Setting the maximum time to 1 hour is not a bad option. And if such options are added?
1) add a switch that, when the file self-deletion option is enabled, as soon as the recording is finished, the video file will be deleted
2) add minutes, now the clock is specified in the settings, it turns out that you can specify the minimum, this is 1 hour, but I would like to specify to delete, for example, every 5 \10\30 minutes
