### ISSUE TITLE
FTP deleting files by timer

### ISSUE THREAD

**Issue by DivanX10** [doitandbedone/ispyagentdvr-docker#330]
In the local storage settings, there is an option to delete files older than 1 hour, but there is no such function in the FTP settings. Could you add such an option, or if there is such an option, how to enable it?

By the way, here is a code that allows you to find and delete files older than any minute, starting from 1 minute.

finds and deletes files older than 1 minute
`find /agent/Media/WebServerRoot/Media/* -name *.* -mmin +1 -delete > /dev/null`

finds and deletes files older than 20 minutes
`find /agent/Media/WebServerRoot/Media/* -name *.* -mmin +20 -delete > /dev/null`

finds and deletes files older than 30 minutes
`find /agent/Media/WebServerRoot/Media/* -name *.* -mmin +30 -delete > /dev/null`

**Comment by ispysoftware** [comment]
yes until storage management runs and removes them from the database
