### ISSUE TITLE
Profiles are not applied to Facial Recognition and Object Recognition

### ISSUE THREAD

**Issue by DivanX10** [doitandbedone/ispyagentdvr-docker#331]
If you apply your own settings for each profile, for example, for the Disabled profile, I turn off Facial Recognition and Object Recognition, then by applying the away profile, they remain in the off state. Changing the profile does not change the settings in Facial Recognition and Object Recognition in any way. Also, if I'm in the Facial Recognition and Object Recognition settings, if I don't turn it off, but just set None for the Disabled profile, and set Detect for the Away profile, then when changing profiles, this also doesn't change. Tell me, is this how it is intended or is it a bug?

![image](https://user-images.githubusercontent.com/64090632/136786536-8f7e1183-51d4-4be4-9a9b-bfe6ca9576be.png)
![image](https://user-images.githubusercontent.com/64090632/136786656-7c99984b-46c8-476c-9266-3763dc42e13c.png)

**Comment by ispysoftware** [comment]
Yeah those settings aren't part of the profile - I can add them to profiles but there will be a limit of settings that profiles store. Originally it was just enabled/ recording / alerts enabled.

**Comment by DivanX10** [comment]
`I can add them to profiles but there will be a limit of settings that profiles store` 
1) Can I tell you more about the limit? 
2) For example, what functions will be available?

**Comment by DivanX10** [comment]
Understood. Thanks. Tell me, and the fact that the 4th Disabled profile is missing in the screenshot, but it is written about it. Is it just that they haven't updated it yet or haven't added 4 profiles to the AgentDVR combat image yet?

![image](https://user-images.githubusercontent.com/64090632/136869376-eef8c1bc-0ccf-48cc-a88a-2b4a1a95e4d0.png)
