### ISSUE TITLE
Server Port doesn't persist between restarts.

### ISSUE THREAD

**Issue by wabragg** [doitandbedone/ispyagentdvr-docker#338]
**Affected Version**
v3.6.2.0

**Describe the bug**
The HTTP server port, that defaults to 8090, does not persist between container restarts if it's changed to 80.  When the container restarts, it jumps back to 8090 and must be set again to 80.

**Steps To Reproduce**
1. Access AgentDVR config and change the server port from 8090 to 80 and save.
2. Reaccess the AgentDVR at the new port 80 to confirm.
3. Restart the container.
4. Attempt to access via port 80 again which will fail.
5. Access AgentDVR back on port 8090 to see that it has flipped back.

**Expected behavior**
Hopefully, persistent storage of the updated server port.

**Reproduction rate**
100%

**Screenshots**

**Host System Information (where ispy agent is running/hosted):**
Synology NAS on DSM 6.2.4.25556 Update 2

**Client System Information (device accessing the web portal, if applicable):**
Any basic browser.

**Additional Information**
This has been a problem for some time ... several versions.  I'm just getting around to letting you know.

**Comment by ispysoftware** [comment]
Thanks have fixed will be in next update

**Comment by wabragg** [comment]
I think your fix didn't work.  I tried 3.7.2.0 and 3.6.9.0 and both don't work if the port is set to 80 from 8090.  Accessing the server then results in some crazy redirect loop where the browser is constantly hitting the site with a parameter like r=0.7274379233 where the number changes constantly.  I was able to get it working again by moving back to 3.6.6.0.  I didn't try others in between.

**Comment by ispysoftware** [comment]
You need to press ctrl-f5 to force reload the page, your web browser has it
cached.

**Comment by wabragg** [comment]
Yup, works fine now.  Port change persists.  I'm back to 3.7.2.0.  I should have caught the cached issue.
