### ISSUE TITLE
Crash when trying to play a timelapse recording

### ISSUE THREAD

**Issue by doitandbedone** [doitandbedone/ispyagentdvr-docker#35]
**Affected version:**
2.8.7.0

**Expected behavior:**
Should be able to play timelapse recordings, if a problem occurs a message should be displayed but should not crash the server.

**Actual Result:**
Server crashes after trying play a timelapse recording.

**Steps to reproduce:**
1. Have at least one timelapse recording in the system.
2. Navigate to Recordings.
3. Select a timelapse recording by clicking/tapping on it.
4. Observe server crashes.

**Reproduction rate:**
100%

**Additional info:**
Here's system and Docker logs:
[CrashLogs.zip](https://github.com/doitandbedone/ispyagentdvr-docker/files/5024995/CrashLogs.zip)
Video causing crash:
https://www.dropbox.com/s/rn7nrd3393c1k1s/2_TimeLapse_2020-08-04_10-38-43.webm?dl=0
@ispysoftware

**Comment by ispysoftware** [comment]
tested here on windows, linux and mac and seems to work fine. I couldn't really see anything in your logs. Does the recording play natively on the mac? Possibly something to do with the length of it or the size of it or something?

**Comment by doitandbedone** [comment]
Videos play fine if played externally. I tried 3 different files and same
behavior. I'll try to run the image on mac and see if it spits out more
details.

**Comment by doitandbedone** [comment]
Hmm... the mac crashes almost right away.
Here are the logs:
[macCrash.zip](https://github.com/doitandbedone/ispyagentdvr-docker/files/5025489/macCrash.zip)

**Comment by ispysoftware** [comment]
try editing media/xml/config.xml and set UseGPU to false, save and start agent again

**Comment by ispysoftware** [comment]
this is running from the docker image right? what happens if you install it normally on the mac without docker? possibly some missing dependency in the image?

**Comment by doitandbedone** [comment]
Away for now. Will get to you as soon as I can. I have a feeling it may be
that as well, since logs mention it.

**Comment by doitandbedone** [comment]
Still crashing:
[gpuOffMacCrash.zip](https://github.com/doitandbedone/ispyagentdvr-docker/files/5025918/gpuOffMacCrash.zip)

**Comment by ispysoftware** [comment]
there's nothing of use in that zip file unfortunately. do you have a console output from it? Also, this is still the docker container version right?

**Comment by doitandbedone** [comment]
Thought so and that is correct

**Comment by doitandbedone** [comment]
That was the docker console output.

**Comment by ispysoftware** [comment]
I setup the latest docker container on my mac and recorded a timelapse with it and it played back fine.

**Comment by doitandbedone** [comment]
The immediate crash isn't happening on the linux docker. I wonder if it's
my setup. It does only crash when trying to do a playback on timelapse
though...

**Comment by doitandbedone** [comment]
Turned off all the devices, still happens unfortunately. One curious thing, I went ahead and tried the lite version of the image and it seems to be able to playback without issues. Could this be a dependency issue?

**Comment by ispysoftware** [comment]
I installed the regular docker version on my mac and it worked fine with recording, timelapse recording and playback.
are there any other locations for crash logs with any meaningful data in them?

**Comment by ispysoftware** [comment]
it's possible that if you updated it some file didn't get updated properly - have you tried a clean install?

**Comment by doitandbedone** [comment]
I did right after that but same result. In a way I been wanting to make
lite image the main and only, but it crashed after a few minutes. master
seems more stable but playback doesn't work for me, I even tried regular
files and it tries to open but doesn't play, but at least it doesn't crash.
What do you think? We move to lite which uses debian and Microsoft's image
with net core and iron out stability, just don't want to be supporting more
than one image. Also want to avoid any new efforts on the old base image.

**Comment by ispysoftware** [comment]
i'm not sure - i dont think it's a code thing as if it was it wouldn't work here. I'm assuming it (playback of files) used to work ok? what changed since?

**Comment by ispysoftware** [comment]
could you upload a recording that is causing a crash on playback?

**Comment by doitandbedone** [comment]
Well, to be honest I'm not sure. The only difference is the ability to
record and trying to play them back. I had played back other videos before,
regular ones with some sluggish behavior, so forced me to rather play them
externally.

As per the docker image, it remained the same other than updating agent. We
did add more cameras but processor tops at 60% and RAM tops at around 30%,
the HDD is 1TB and it's around 30gb used, so resources shouldn't be a
problem.

**Comment by ispysoftware** [comment]
are you viewing the recordings on the host or on another computer/ mobile device on the network? possibly there's some buffer over-run issue caused by network delay..

**Comment by doitandbedone** [comment]
From another device in network. The host is just a server.

**Comment by doitandbedone** [comment]
Here's the video:
https://www.dropbox.com/s/rn7nrd3393c1k1s/2_TimeLapse_2020-08-04_10-38-43.webm?dl=0

**Comment by ispysoftware** [comment]
I'm having zero luck reproducing it - copied that file to my mac and renamed it to match an existing one and it played fine. Everything i'm trying on windows, mac and linux, in and out of regular docker and lite docker containers is working.
The only way to make progress is to get a decent error message from it.
Take a look at
https://medium.com/@pimterry/5-ways-to-debug-an-exploding-docker-container-4f729e2c0aa8
see if there's any useful info.

**Comment by doitandbedone** [comment]
Ran it again without letting it restart and still the same. As far as log collection, it most probably just does not print the error onto the console. I am already using -it and collecting logs from the container.
The only errors the logs pit out are:
```
[37m[40mOffice: Failed to create specified HW device.

[37m[40mOffice: Failed to create specified HW device.

[32m[40m[h264 @ 0x145b18006f80] A hardware frames or device context is required for hardware accelerated decoding.
[32m[40m[h264 @ 0x145b18006f80] Failed setup for format vaapi_vld: hwaccel initialisation returned error.

[37m[40mICE state: Checking
[37m[40mLiving Room: Failed to create specified HW device.

[32m[40m[h264 @ 0x145af40074c0] A hardware frames or device context is required for hardware accelerated decoding.
[32m[40m[h264 @ 0x145af40074c0] Failed setup for format vaapi_vld: hwaccel initialisation returned error.

[32m[40m[swscaler @ 0x145a98f57180] Warning: data is not aligned! This can lead to a speed loss

[37m[40mSignalR: Services Connected
[37m[40mWelcome: doitandbedone
[37m[40mConnected - access this server via https://www.ispyconnect.com/
[37m[40mloaded
[37m[40mVan Parking: Failed to create specified HW device.

[32m[40m[h264 @ 0x145b2c02f700] A hardware frames or device context is required for hardware accelerated decoding.
[32m[40m[h264 @ 0x145b2c02f700] Failed setup for format vaapi_vld: hwaccel initialisation returned error.

[37m[40mGym (PTZ): Failed to create specified HW device.

[32m[40m[h264 @ 0x145b14002540] A hardware frames or device context is required for hardware accelerated decoding.
[32m[40m[h264 @ 0x145b14002540] Failed setup for format vaapi_vld: hwaccel initialisation returned error.

[37m[40mStudio: Failed to create specified HW device.

[32m[40m[h264 @ 0x145b1c008c00] A hardware frames or device context is required for hardware accelerated decoding.
[32m[40m[h264 @ 0x145b1c008c00] Failed setup for format vaapi_vld: hwaccel initialisation returned error.

[37m[40mFront Door: Failed to create specified HW device.

[32m[40m[h264 @ 0x145b2400bc80] A hardware frames or device context is required for hardware accelerated decoding.
[32m[40m[h264 @ 0x145b2400bc80] Failed setup for format vaapi_vld: hwaccel initialisation returned error.

[37m[40mBridge: Failed to create specified HW device.

[32m[40m[h264 @ 0x145b10026fc0] A hardware frames or device context is required for hardware accelerated decoding.
[32m[40m[h264 @ 0x145b10026fc0] Failed setup for format vaapi_vld: hwaccel initialisation returned error.
```
It's literally the last lines printed. I did notice these are printed regardless, and they are marked as warning in the console, which makes me believe it's not the actual error. Not sure why a stacktrace is not being printed, perhaps a handled exception with no prints?

**Comment by ispysoftware** [comment]
Is it crashing or hanging?

**Comment by doitandbedone** [comment]
It crashes.

**Comment by ispysoftware** [comment]
You should be able to run it under a debugger. Take a look at https://github.com/dotnet/runtime/issues/9759&ved=2ahUKEwiSpvL_lYXrAhWGc30KHZXOBxIQFjAAegQIARAC&usg=AOvVaw2f92rtDFShsPlPcC6Ys9LC

**Comment by ispysoftware** [comment]
did the debugger help?

**Comment by doitandbedone** [comment]
Haven't had the chance to look at it yet. I'll try it tomorrow. Thanks for
the suggestion.

**Comment by ispysoftware** [comment]
made a couple of updates today - try with 2.8.9.0

**Comment by doitandbedone** [comment]
Updated, still crashing. As far as runtime. Is the code open source?
Otherwise I don't think it can be debugged. The link you sent me is for the
issues page and there's none. Not sure if you wanted me to take a look at a
specific one?

**Comment by ispysoftware** [comment]
It's the same issue you are facing - an exit without an error message.
https://github.com/dotnet/runtime/issues/9759

the advice there was:

"Could you please run it under a debugger (gdb or lldb)?

To run it under gdb:

gdb --args dotnet TestCrash.dll
To run it under lldb:

lldb -- dotnet TestCrash.dll
In both debuggers, then use the r command to run the app
If it succeeds, use the quit command to exit the debugger again.
If it hits the abort, run the bt command in the debugger and get me the output."

I can send you a debug version of it but i don't think it will help much. If it's just exiting to the console without printing any kind of reason then something on a deeper level than the application is having a problem.

**Comment by doitandbedone** [comment]
Ah I see it now. I'll check it out thanks!

**Comment by ispysoftware** [comment]
did you get an error report using that?

**Comment by doitandbedone** [comment]
Sorry haven't had a chance just yet :/. Will get back to you as soon as
possible!

**Comment by doitandbedone** [comment]
I tired gdb as seems to be simpler to implement. I tried it on a docker image on the mac, it seems to freeze up after about a minute of booting however. Will try on the linux docker next.

**Comment by doitandbedone** [comment]
Did try but the logs were not helpful at all. After updating last night the issue went away. I was 3 versions behind however. But I can say as of version 2.9.8.0 the issue seems to be resolved.

**Comment by ispysoftware** [comment]
errr.. ok! no idea what was going on there
