### ISSUE TITLE
 SignalR: SignalR: The operation was canceled.

### ISSUE THREAD

**Issue by pumucklll** [doitandbedone/ispyagentdvr-docker#369]
**Affected Version**
v3.7.8.0

**Describe the bug**

Hello,
It is not possible to connect the local agent with the subscription.

 The Installation with Docker does not work, even after an update. 

With windows and Linux installation, it is ok

Looks like rtcfunc.azurewebsites.net is not reachable.

full Log is attached:
CheckReconnect: Reconnecting signalr
22:04:48 Using comms server https://rtcfunc.azurewebsites.net/
22:04:48 Connecting service (https://rtcfunc.azurewebsites.net/)
22:05:03 SignalR: SignalR: The operation was canceled.
22:05:03 Error: SignalR: SignalR: The operation was canceled.

![image (1)](https://user-images.githubusercontent.com/47299110/153423593-d9ff457e-9137-4729-9182-27312ebeb106.png)

**Steps To Reproduce**
after this command:

docker run -it -p 8090:8090 -p 3478:3478/udp -p 50000-50010:50000-50010/udp \ -v /appdata/ispyagentdvr/config/:/agent/Media/XML/ \ -v /appdata/ispyagentdvr/media/:/agent/Media/WebServerRoot/Media/ \ -v /appdata/ispyagentdvr/commands:/agent/Commands/ \ -e TZ=America/Los_Angeles \ --name agentdvr doitandbedone/ispyagentdvr

**Reproduction rate**
How often does this happen in % 100% 

**Host System Information (where ispy agent is running/hosted):**

Vmware Esxi; Vm Openmediavault Debian;: Dockercontainer

**Client System Information (device accessing the web portal, if applicable):**

 - Browser  chrome safari

**Additional Information**
maybe not all ports provided to the container?

Greetings

**Comment by doitandbedone** [comment]
Hello @pumucklll. What version did you initially encounter this problem?

**Comment by pumucklll** [comment]
I didn't used my agent for about 6  months.
Now I extended my subscription and I just though that I have to reconnect.
I couldn't connect, so I made an update.

this is from the agentDVR.xml file, before I made the update:
<?xml version="1.0" encoding="utf-16"?>
<objects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Version>3660</Version>


Just now I made a test with 3.5.7.0] with the same result
first try:
![image](https://user-images.githubusercontent.com/47299110/153479838-7d174a4b-05ca-49fd-86e3-20cb9c2a44af.png)
second try to connect
![image](https://user-images.githubusercontent.com/47299110/153480141-8908d555-f37a-4b8b-87f6-d06fdb200fac.png)

![image](https://user-images.githubusercontent.com/47299110/153480195-330dee9c-8d9a-4460-8fd5-6da5fb31200a.png)

**Comment by ispysoftware** [comment]
I'm guessing it's something to do with running behind a proxy..

https://github.com/aspnet/SignalR/issues/2829#issuecomment-414226921

?
