### ISSUE TITLE
New version unavailable

### ISSUE THREAD

**Issue by titiviking** [doitandbedone/ispyagentdvr-docker#386]
**Affected Version**
Found at top left "Server Menu" with a server/stack icon. A pop up will be opened, should be in bold letters to the right of your server name. [e.g. v3.0.0.0]

**Describe the bug**
According to the GUI, version 3.8.8 is available. However using docker pull command on image doitandbedone/ispyagentdvr:latest I’m only able to retrieve version 3.8.6.
 
```
root@DiskStation:~# docker pull doitandbedone/ispyagentdvr:latest
latest: Pulling from doitandbedone/ispyagentdvr
Digest: sha256:1f424092007eab2747aa4500fa68c33e4c10a6199b1291496f79dcd7fae56682
Status: Image is up to date for doitandbedone/ispyagentdvr:latest
[docker.io/doitandbedone/ispyagentdvr:latest](http://docker.io/doitandbedone/ispyagentdvr:latest)
```
 
 
![image](https://user-images.githubusercontent.com/73351833/160093200-794911bc-7282-44ac-b013-37000674f556.png)

 
Could you clarify how I can get the latest update (or notify me when image was updated on DockerHub) ?

**Steps To Reproduce**

**Expected behavior**

**Reproduction rate**
How often does this happen in % [e.g. 100% or 50%]

**Screenshots**

**Host System Information (where ispy agent is running/hosted):**
 - OS: [e.g. macOS Catalina 10.15.7, Windows 10, Ubuntu 20.04.1 LTS]

**Client System Information (device accessing the web portal, if applicable):**
 - OS: [e.g. macOS Catalina 10.15.7, iOS 8.1, Windows 10, Android 10, Ubuntu 20.04.1 LTS]
 - Browser [e.g. stock browser, safari, chrome]
 - Browser Version [e.g. 86.0.4240.111 (Official Build) (x86_64)]

**Additional Information**
Add any other information about the problem here. This could include configuration files, video/images that may be causing the issue.

**Comment by doitandbedone** [comment]
As stated before docker version may be behind and users must either wait or pull the specific versions from tags. I approved 3.8.6. should abe available on a few minutes.
