### ISSUE TITLE
Cyrillic fonts on labels in Timestamp

### ISSUE THREAD

**Issue by Sandteufel** [doitandbedone/ispyagentdvr-docker#391]
Hi! I use Agent as docker ( test as native in lunux) 
I set language to Russian and found that all interface is very good but labels on photos and videos is with broken fonts/ I see only ???????. It is as result of using OpenCV.

How repair this? Is i found, that its work on windows installation, but installing win only for correct symbols...

**Comment by ispysoftware** [comment]
opencv only has one font unfortunately
have you tried unchecking "Use OpenCV to render text" on Server settings - playback?

**Comment by ispysoftware** [comment]
support for cyrillic fonts has been added
