### ISSUE TITLE
Turn Server Port Conflict

### ISSUE THREAD

**Issue by mpjanofsky** [doitandbedone/ispyagentdvr-docker#40]
UDP 3478 is used by other containers and causes a conflict, thus the container does not work properly. The conflict I'm having is with the Unifi Controller. Not sure if this is specific to this image or a bigger docker issue?

**Comment by ispysoftware** [comment]
You can change the port in the config. From the notes in the dockerfile:

# Docker needs to run a TURN server to get webrtc traffic to and from it over forwarded ports from the host
# These are the default ports. If the ports below are modified here you'll also need to set the ports in XML/Config.xml
# for example <TurnServerPort>3478</TurnServerPort><TurnServerMinPort>50000</TurnServerMinPort><TurnServerMaxPort>50010</TurnServerMaxPort>
# The main server port is overridden by creating a text file called port.txt in the root directory containing the port number, eg: 8090
# To access the UI you must use the local IP address of the host, NOT localhost - for example http://192.168.1.12:8090/

**Comment by doitandbedone** [comment]
You can also have docker forward the port in the host from any port you
choose to the one the image asks when passing the port parameter:
-p <host-port>:<container-port>.

For instance if the container calls for port 8090 but you use that port for
another container you can swap it for any other one you'd like, in this
case 8190:
-p 8190:8090

For more info see the documentation here:
https://docs.docker.com/config/containers/container-networking/

**Comment by ispysoftware** [comment]
I don't think that would help with the turn port as the ui will be telling the client what port to connect on which will be 3478 no matter which port you have forwarded to the container - it needs to be set in the xml config unfortunately.

**Comment by mpjanofsky** [comment]
@ispysoftware Changing the default TURN server port in config.xml did the trick. Thanks!
