### ISSUE TITLE
Constantly fluctuating RAM usage

### ISSUE THREAD

**Issue by 0kashi** [doitandbedone/ispyagentdvr-docker#401]
**Affected Version**
3.9.5.0

**Describe the bug**
Not sure this is a bug, but not expected behavior. I noticed that while recording memory consumption slowly increases until it's maxed out then it will drop when storage management runs, then again it continues to increase again until storage management runs again.  Creating a sawtooth pattern. I have attached a screenshot.

What is causing this? Is this normal behavior? 

**Steps To Reproduce**
Let ispy run with cameras recording and turn on storage management

**Expected behavior**
I'd expect RAM usage to be more/less constant over time.  Not to have a sawtooth pattern. I'd expect the container to be using the attached PersistentVolumes rather than RAM.

**Reproduction rate**
As long as I have been running storage management.

**Screenshots**

<img width="1313" alt="Screen Shot 2022-05-10 at 9 54 27 AM" src="https://user-images.githubusercontent.com/55109335/167693502-59de66b0-0674-4108-993b-e5d52b8120c4.png">

**Host System Information (where ispy agent is running/hosted):**
Proxmox VM, Ubuntu Server 20.04

**Comment by ispysoftware** [comment]
not a bug unless it runs out of memory and crashes- it's just the way .net handles memory pressure and cpu load 
https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals

if it does run out of memory you might have too many clients/ cameras connected to it.
