### ISSUE TITLE
Lastest version? 

### ISSUE THREAD

**Issue by Oxize** [doitandbedone/ispyagentdvr-docker#410]
Do you have an docker images with version 4.0.0.0? or 3.9.x.x?

When i add your latest, i get only an image from version 3.6.9.0 which is from 11/05/2021? Why not upgrade to the latest?

**Comment by al-geeker** [comment]
I also want to use the latest Docker tag.

I used doitandbedone/ispyagentdvr:latest to get the latest version of Agent DVR.

But when I check the version, I see 4.0.0.0

Is the Docker image up to date?

**Comment by al-geeker** [comment]
I think this might be the issue. The latest tag was last updated 21 days ago.

![image](https://user-images.githubusercontent.com/32320831/174702622-e9925475-cea2-49cc-a77a-f5f00c0a06e9.png)

**Comment by doitandbedone** [comment]
Updated
