### ISSUE TITLE
Google Nest Hello Doorbell Camera Not Working

### ISSUE THREAD

**Issue by kensagle** [doitandbedone/ispyagentdvr-docker#433]
**Affected Version**
Home v4.1.1.0

**Describe the bug**
I am not able to get google nest hello doorbell cam (wired) to work in ispyagentdvr.  I shared the public stream and put in the link and it found the stream link, but it will not connect.  I can view this stream in VLC and website streaming without issue.

**Steps To Reproduce**
Add google nest hello camera using the nest option.

**Expected behavior**
I expect the video to show in the dashboard and fucntion like my other 12 cameras

**Reproduction rate**
100%

**Screenshots**

**Host System Information (where ispy agent is running/hosted):**
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
Linux NAS 5.11.0-46-generic #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Client System Information (device accessing the web portal, if applicable):**
Multiple Windows 10, Ubuntu 20.04, Chrome.  All show same behavior

**Additional Information**
Add any other information about the problem here. This could include configuration files, video/images that may be causing the issue.

**Comment by ispysoftware** [comment]
you'll need to send me the url to test (via contact us on the website) 
https://www.ispyconnect.com/contact.aspx

**Comment by ispysoftware** [comment]
no response
