### ISSUE TITLE
Missing alsa-utils dependency

### ISSUE THREAD

**Issue by trevnels** [doitandbedone/ispyagentdvr-docker#434]
**Affected Version**
`v4.1.1.0`

**Describe the bug**
Agent DVR fails to scan for local audio devices on startup. It tries to run `arecord -l` but this fails since the package `alsa-utils` isn't present inside the container. Because of this, no audio devices are available in the UI.

I can manually install the package in the container by doing an apt update then apt install alsa-utils, but this doesn't stick when restarting it. However this does allow me to access my audio devices through the UI (until the container restarts)

**Steps To Reproduce**
1. Connect a USB audio device and ensure it is passed to the container (I'm using a Logitech C920 and its microphone)
2. Start up the container
3. Observe that the audio device isn't available when adding a new device and the error listed below is recorded in the logs during startup.

**Expected behavior**
The C920 microphone is available as an audio device in the UI, with no alsa-related errors in the logs.

**Reproduction rate**
100%

**Screenshots / Log**
```
...
8:55:36 PM | call arecord -l
8:55:36 PM | CMD: CMD: No such file or directory
8:55:36 PM | Error: CMD: CMD: No such file or directory
8:55:36 PM | CMD:     at System.Diagnostics.Process.ForkAndExecProcess(String filename,  String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean  redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32  userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32&  stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean  throwOnNoExec)    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)    at System.Diagnostics.Process.Start()    at CoreLogic.Utilities.CMD.GetOutput(String exe, String strCommand)
8:55:36 PM | Error:  CMD:    at System.Diagnostics.Process.ForkAndExecProcess(String  filename, String[] argv, String[] envp, String cwd, Boolean  redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean  setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups,  Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean  usesTerminal, Boolean throwOnNoExec)    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)    at System.Diagnostics.Process.Start()    at CoreLogic.Utilities.CMD.GetOutput(String exe, String strCommand)
8:55:36 PM | No such file or directory
8:55:36 PM | No audio devices found
8:55:36 PM | Error: No audio devices found
...
```

![no-devices](https://i.imgur.com/tXEzNSk.png)

**Host System Information (where ispy agent is running/hosted):**
 - OS: TrueNAS-SCALE-22.02.3 (Debian-based)
 - `Linux truenas 5.10.131+truenas #1 SMP x86_64 GNU/Linux`

**Additional Information**
It looks like adding `alsa-utils` to the dependencies of the Dockerfile (line 14) should fix this.

**Comment by doitandbedone** [comment]
This should be taken care of on version 4.1.2.0
