### ISSUE TITLE
update for 4.1.2.0

### ISSUE THREAD

**Issue by ispysoftware** [doitandbedone/ispyagentdvr-docker#435]
Agent v4.1.2.0+ has been updated to use the .net 6 runtime and ffmpeg v5 - the new code doesn't need a separate .net core install, it's all in a self contained executable.

prob best to base this off ubuntu 22 as that has ffmpeg v5 available as a package install

latest setup script for linux:

https://github.com/ispysoftware/agent-install-scripts/blob/main/v2/linux_setup.sh

**Comment by sirweazel** [comment]
Question. I'm currently using the latest docker image.  I'm using a docker compose/portainer stack to manage this instance.  I see it is on 4.1.1.0 and the notification says to run the update script in the docker container.  Should i do this, or just wait for the docker image to be updated, then whenever the convenient docker image is updated, I can just pull down the updated image?  Note: I'm fairly new to docker, and this is my 3rd project where i've been messing around with it.  So i'm still wrapping my head around it.  But from the update notificaiton in the application, it sounds like i need to open up a special docker terminal inside the docker image to run the script (i think i did this once before when messing around with HA).  Thanks!

**Comment by ispysoftware** [comment]
just wait

**Comment by doitandbedone** [comment]
@sirweazel I'll post the changes as soon as I get them running properly, still going over new changes compared to older versions. You may go over them once they are published. I've created a new branch 4.1.2.0 if you want to see a preview as I make the changes!

**Comment by doitandbedone** [comment]
@ispysoftware @sirweazel 
Changes are live, the image should generate soon. You can check the new tag 4.1.2.0 for details.

Let me know if you find any issues.

**Comment by sirweazel** [comment]
@doitandbedone 
Great job!  I'm only 5 min in, but after applying the updated container (latest tag worked) it has the new version.  Everything appears to have picked back up where it left off so no breaking changes in any of the persisted configs.  I only have about 6 hours into trying out ispy agent DVR, so I'm not entirely sure I would notice an issue related to the update, but I'll post if i do.  I have 3 cameras added trying out various detection methods, and I'm in the 7 day trial window of the Android app which appears to have connected fine after the update.  So thanks for the quick response time!  I have a couple comments/questions, so i just need to find the appropriate place to ask them.
