### ISSUE TITLE
Publication issue for vlc-support branch

### ISSUE THREAD

**Issue by titiviking** [doitandbedone/ispyagentdvr-docker#493]
After approval of initial PR master branch is properly updated.

New PR for other branches are created although not processed for publication.

This issue is more of a heads up to take a look at the process.
I'm myself a user of the vlc-support release and eagerly waiting to test out the new bug fixes and improvements I need that fixes some onvif issues within latest release.

**Comment by doitandbedone** [comment]
Resolved
