### ISSUE TITLE
missing commands folder

### ISSUE THREAD

**Issue by ispysoftware** [doitandbedone/ispyagentdvr-docker#495]
getting reports that commands list is empty  (server menu, commands)
- the setup script is missing a / at the end of commands, not sure if this is the issue?

docker run -it -p 8090:8090 -p 3478:3478/udp -p 50000-50010:50000-50010/udp \
-v /appdata/ispyagentdvr/config/:/agent/Media/XML/ \
-v /appdata/ispyagentdvr/media/:/agent/Media/WebServerRoot/Media/ \
-v /appdata/ispyagentdvr/commands/:/agent/Commands/ \
-e TZ=America/Los_Angeles \
--name ispyagentdvr doitandbedone/ispyagentdvr

**Comment by alexbn71** [comment]
Hi Sean, no this is not cause. Docker doesn't copy the content of the folder on the destination volume. 

...a question ... does the /config folder already contain files or are they generated at the first start?

**Comment by doitandbedone** [comment]
If the folder already exists, aka there from older versions it will persist
whatever is there from host. This is setup on command ir by user on the
first time. As for the container or the app. It has files on the first
install that docker will pass on to the host and persist from that point on.

**Comment by alexbn71** [comment]
Yes this is the theory :) but in realty it doesn't happen this way. I've installed the image without the folder already present and "commands" folder is created empty. I've verified this on two different machine.

**Comment by doitandbedone** [comment]
Oh commands. That's different, you asked for /config which should be
populated

**Comment by alexbn71** [comment]
I asked for /config to Sean because this folder is correctly populated.  Instead /commands that should contains some files it's always empty.

**Comment by alexbn71** [comment]
As suspected the "Media" folder where resides "Config" folder, is created by AgentDVR on first start and populated with default files... instead the "Commands" folder is already present (and populated) in the .zip package of the software. This explain why "config" folder behaviour is different from "commands".

The mistery is why /Commands content isn't replicated on host path

**Comment by alexbn71** [comment]
After some searches on GG I found that when you mount a host directory into container, the contents of host directory shadow the contents of container. For this reason it's empty after install. To avoid this, named volumes should be used... but named volumes resides on docker installation path and and they are not comfortable to use all the time.

**Comment by ispysoftware** [comment]
i've updated it to store all content in a content folder and install it to the relevant locations on first run

**Comment by alexbn71** [comment]
Thank you :)

**Comment by doitandbedone** [comment]
@ispysoftware Is this still an issue? Since it's reopened.

**Comment by alexbn71** [comment]
Tested now in 4.3.3.0... \Commands folder is still empty

**Comment by ispysoftware** [comment]
should be copying the commands in there on start, same as it does for masks and sounds - check the logs

**Comment by doitandbedone** [comment]
Closed as resolved
