### ISSUE TITLE
local time is wrong in container

### ISSUE THREAD

**Issue by ispysoftware** [doitandbedone/ispyagentdvr-docker#501]
Seems there's an issue with the new dotnet version 6 where calls to get the local time are returning UTC time which is messing with scheduling

https://github.com/dotnet/runtime/issues/62545#issuecomment-990446585

I think the trick is to run

unlink /etc/localtime

**Comment by doitandbedone** [comment]
@ispysoftware Does this need to be added to the image then?

**Comment by ispysoftware** [comment]
yes

**Comment by doitandbedone** [comment]
Is this still an issue? I see the issue link is closed.
