### ISSUE TITLE
HTTP Streaming

### ISSUE THREAD

**Issue by DivanX10** [doitandbedone/ispyagentdvr-docker#506]
**Is your feature request related to a problem? Please describe.**
There is [PiPup](https://github.com/desertblade/PiPup) integration for Home Assistant, which allows you to display a picture from a video or a photo from a camera on TV screens, you can also output a stream. AgentDVR has only RTMP Streaming, and HTTP Streaming is needed

**Describe the solution you'd like**
I ask you to implement HTTP Streaming as far as possible, as it is implemented in [Motion Eye addon](https://github.com/hassio-addons/addon-motioneye)

**Describe alternatives you've considered**
An alternative implementation of HTTP Streaming is available from [Motion Eye addon](https://github.com/hassio-addons/addon-motioneye)

**Additional context**
![image](https://user-images.githubusercontent.com/64090632/195362593-c33e9ca6-c7b9-4382-b3b5-e59dfd91955d.png)

**Comment by ispysoftware** [comment]
https://www.ispyconnect.com/userguide-agent-api.aspx

see 
video.mjpg

**Comment by DivanX10** [comment]
I don't understand. How is it correct to enter a command in the http line to output one camera out of two?

http://192.168.1.50:8090/command.cgi?cmd=video.mjpg?oid=1&size=320x240
http://192.168.1.50:8090/#command.cgi?cmd=video.mjpg?oid=1&size=320x240
http://192.168.1.50:8090/cmd=video.mjpg?oid=1&size=320x240
http://192.168.1.50:8090/video.mjpg?oid=1&size=320x240

**Comment by DivanX10** [comment]
Вопрос снялся. оказывается надо было делать вот так
```
http://192.168.1.50:8090/video.mjpg?oid=1&size=640x480
```

Код наверху выводит камеру с белым фоном и чтобы фон сделать черным я использовал вот такой вариант
```
http://192.168.1.50:8090/video.mjpg?oid=1&size=640x480&backColor=0,0,0

```
