### ISSUE TITLE
[Feature Request] VLC support

### ISSUE THREAD

**Issue by Rafi594** [doitandbedone/ispyagentdvr-docker#51]
Hello

I have some cameras who doesn't want to work with FFMPEG but are working with VLC. But the docker image doesn"t seems to include VLC. I have tried to install it manually with `docker exec agentdvr apt-get install -yy libvlc-dev` but it does not work.

**Comment by ispysoftware** [comment]
Had to update some code to get vlc working on linux, it'll be in the next update

https://code.videolan.org/videolan/LibVLCSharp/blob/master/docs/linux-setup.md

**Comment by doitandbedone** [comment]
I've also made a change to use CMD instead of ENTRYPOINT to offer a bit more flexibility. Should be up in the next dockerfile update.

**Comment by ispysoftware** [comment]
should be resolved - let me know

**Comment by doitandbedone** [comment]
@Rafi594 you mind confirming please?

**Comment by Rafi594** [comment]
It's working after installing libvlc-dev vlc and libx11-dev

**Comment by ispysoftware** [comment]
@doitandbedone  you want to add those to the docker file?

**Comment by doitandbedone** [comment]
Sure. I'll add them as soon as possible. Driving for a while.

**Comment by doitandbedone** [comment]
@ispysoftware Hmm, after further review, this don't you think this should be an optional item? It'll just add more space to the image and users may end up not using it. I would add the instructions however.

**Comment by ispysoftware** [comment]
sure sounds good
