### ISSUE TITLE
Setting the time to Eastern standard.

### ISSUE THREAD

**Issue by gplamondon** [doitandbedone/ispyagentdvr-docker#521]
How do I change the time to America/Detroit so that the camera time overlay reflects local EDT time?

**Comment by ispysoftware** [comment]
set the local timezone
https://support.circleci.com/hc/en-us/articles/115015771347-How-do-I-set-the-timezones-in-Docker-images-

.. or set the GMT offset on the timestamp tab when editing the camera

**Comment by doitandbedone** [comment]
That's what the enviroment variable `-e TZ=America/Los_Angeles` is for when y9u run the command. Set it based on whatever engine you are using.
