### ISSUE TITLE
Reolink Duo 2 Wifi is not in the device list en does not connect

### ISSUE THREAD

**Issue by MarnixReadolmen** [doitandbedone/ispyagentdvr-docker#543]
I have a Reolink Duo 2 Wifi that is not in the device list en that is not connectiing with agent dvr. If I add it with the previous Reolink Duo Wifi, it provides the streams, but after selection, it does not connect.  Can you add that device to your list? Do you have tips to connect this device to agent dvr?

**Comment by ispysoftware** [comment]
Hello if you can port forward it and PM me a link with a login to it (and it's rtsp port) then I can take a look - i don't have one here to test with.
