### ISSUE TITLE
ONVIF Event Errors

### ISSUE THREAD

**Issue by Dvalin21** [doitandbedone/ispyagentdvr-docker#561]
Agent DVR 4.5.2.0.

**Describe the bug**

Needing help getting this situated. Getting the following ONVIF errors.

23:12:ONVIF State Monitor: Front Door: Onvif event receiver state: Connection error: The request channel timed out attempting to send after 00:00:15. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.

23:12:ONVIF Events: Front Door: Ignored ONVIF event: <tt:source xmlns:tt="http://www.onvif.org/ver10/schema"><tt:simpleitem name="videosource" value="v_src_000" /><tt:simpleitem name="rule" value="mytamperdetectorrule" /></tt:source><tt:data xmlns:tt="http://www.onvif.org/ver10/schema"><tt:simpleitem name="istamper" value="false" /></tt:data>

Also

20:39:AI Facial Recognition: AI Facial Recognition: Object reference not set to an instance of an object.
20:39:Error: AI Facial Recognition: AI Facial Recognition: Object reference not set to an instance of an object.
20:39:AI Facial Recognition:    at CoreLogic.AI.FaceRecognizer.ProcessResults(FaceResponse resp, String json, Mat f) at CoreLogic.AI.FaceRecognizer.Detect()
20:39:Error: AI Facial Recognition:    at CoreLogic.AI.FaceRecognizer.ProcessResults(FaceResponse resp, String json, Mat f) at CoreLogic.AI.FaceRecognizer.Detect()
20:39:Object reference not set to an instance of an object.
20:39:Will retry AI processing in 30 seconds.

**Expected behavior**

**Reproduction rate**
How often does this happen in % [e.g. 100% or 50%] 100%

**Host System Information (where ispy agent is running/hosted):**
 - OS: Ubuntu Server/CasaOS v4.1 docker-compose

**Additional Information**

Camera Info

[Anibux A8SB 4K Dual Lens 8mp](https://www.aliexpress.us/item/3256804577822128.html?spm=a2g0o.order_list.order_list_main.5.3a2518026iQMio&gatewayAdapt=glo2usa&_randl_shipto=US)

20:58:Discovery: Front Door: Media available at http://x.x.x.x:8899/onvif/media2_service
20:58:Discovery: Front Door: PTZ available at http://x.x.x.x:8899/onvif/ptz_service
20:58:Discovery: Front Door: Events available at http://x.x.x.x:8899/onvif/event_service
20:58:PTZ Discovery: Front Door: Could not get PTZ config for Onvif Device - using defaults

**Comment by ispysoftware** [comment]
This is just saying that your camera isn't responding to events polling.
If you want it to respond to your custom rule you can add

<tt:simpleitem name="istamper" value="true" />

to server settings - onvif settings as a custom string to look for

**Comment by Dvalin21** [comment]
Thanks for the response. So, I didn't realize this was for custom rules. I
just set the camera up for Onvif and turned on Onvif in Detector. Is there
good documentation on adding custom rules to "Detect XML"?

**Comment by ispysoftware** [comment]
it's just looking for a substring match so any substring in the "ignored onvif event" log entry will make it not ignore that event and treat it as a motion event.

**Comment by Dvalin21** [comment]
> it's just looking for a substring match so any substring in the "ignored onvif event" log entry will make it not ignore that event and treat it as a motion event.

So after putting in the entry I get the following

21:04:StartSaving: Front Door: 
21:04:Front Door: StartSaving: Front Door: StartSaving: Transport endpoint is not connected : '/agent/Media/WebServerRoot/Media/video/RJYWS/'
21:04:Error: Front Door: StartSaving: Front Door: StartSaving: Transport endpoint is not connected : '/agent/Media/WebServerRoot/Media/video/RJYWS/'
21:04:Front Door: StartSaving:    at System.IO.FileSystem.CreateDirectory(String )
   at System.IO.Directory.CreateDirectory(String )
   at CoreLogic.Objects.AgentControlBase.OpenWriter()
21:04:Error: Front Door: StartSaving:    at System.IO.FileSystem.CreateDirectory(String )
   at System.IO.Directory.CreateDirectory(String )
   at CoreLogic.Objects.AgentControlBase.OpenWriter()
21:04:Transport endpoint is not connected : '/agent/Media/WebServerRoot/Media/video/RJYWS/'
21:04:StartSaving: Front Door: Retry in 5 seconds

**Comment by Dvalin21** [comment]
And also 

21:04:ONVIF Events: Front Door: Ignored ONVIF event: <tt:source xmlns:tt="http://www.onvif.org/ver10/schema"><tt:simpleitem name="videosource" value="v_src_000" /><tt:simpleitem name="rule" value="mytamperdetectorrule" /></tt:source><tt:data xmlns:tt="http://www.onvif.org/ver10/schema"><tt:simpleitem name="istamper" value="false" /></tt:data>
21:04:ONVIF Received: <tt:Source xmlns:tt="http://www.onvif.org/ver10/schema"><tt:SimpleItem Name="VideoSource" Value="V_SRC_000" /><tt:SimpleItem Name="Rule" Value="MyMotionDetectorRule" /></tt:Source><tt:Data xmlns:tt="http://www.onvif.org/ver10/schema"><tt:SimpleItem Name="State" Value="false" /></tt:Data>
21:04:ONVIF Received: <tt:Source xmlns:tt="http://www.onvif.org/ver10/schema"><tt:SimpleItem Name="Source" Value="V_SRC_000" /></tt:Source><tt:Data xmlns:tt="http://www.onvif.org/ver10/schema"><tt:SimpleItem Name="State" Value="false" /></tt:Data>
21:04:ONVIF Received: <tt:Source xmlns:tt="http://www.onvif.org/ver10/schema"><tt:SimpleItem Name="InputToken" Value="DIGIT_INPUT_000" /></tt:Source><tt:Data xmlns:tt="http://www.onvif.org/ver10/schema"><tt:SimpleItem Name="LogicalState" Value="false" /></tt:Data>

**Comment by ispysoftware** [comment]
do any of these events contain the text you entered?

**Comment by Dvalin21** [comment]
> do any of these events contain the text you entered?

No
