### ISSUE TITLE
OK and  Cancel buttons duplicated and displayed incorrectly

### ISSUE THREAD

**Issue by doitandbedone** [doitandbedone/ispyagentdvr-docker#57]
Version: v2.9.3.0

Details:
OK and Cancel buttons are displayed incorrectly (no text) and duplicated for some pop up windows.
Affected areas: Settings, Edit Devices, Profiles

![Screen Shot 2020-09-17 at 5 28 04 PM](https://user-images.githubusercontent.com/61026996/93541517-89cb9b00-f90b-11ea-8052-e2c52c6e49eb.png)

**Comment by ispysoftware** [comment]
I think this is a browser caching issue - can you try a force refresh on it

**Comment by doitandbedone** [comment]
I tried incognito, and the issue is gone. I restarted the normal session but the issue persists, I even deleted the cookies and restarted but no luck.

**Comment by ispysoftware** [comment]
is this on chrome? shift-f5 should do the trick

**Comment by doitandbedone** [comment]
Yes it's chrome, away from the computer. I'll try it as soon as I get back
home.

**Comment by ispysoftware** [comment]
did the update resolve your issue?

**Comment by doitandbedone** [comment]
Seems to have gone away by itself after I came back the next day. Odd... closing anyhow.
