### ISSUE TITLE
ffmpeg 6 error since 4.9.2.0

### ISSUE THREAD

**Issue by traktuner** [doitandbedone/ispyagentdvr-docker#640]
**Affected Version**
>=4.9.2.0

**Describe the bug**
When starting the container, this error appears:
Agent DVR: Installing FFmpeg 6

**Host System Information (where ispy agent is running/hosted):**
 - OS: Synology x86_64 Docker host

**Additional Information**
In the Dockerfile, ffmpeg 5 is being installed - I don't know if that is the issue.
Or maybe it's a new behaviour from the ispy agent setup.

**Comment by ispysoftware** [comment]
When Agent starts up first time it installs ffmpeg v6. This version of the docker doesn't look like it's being maintained any more - try this one instead

https://hub.docker.com/r/mekayelanik/ispyagentdvr

**Comment by traktuner** [comment]
> When Agent starts up first time it installs ffmpeg v6. This version of the docker doesn't look like it's being maintained any more - try this one instead
> 
> https://hub.docker.com/r/mekayelanik/ispyagentdvr

Thank you!

**Comment by ispysoftware** [comment]
https://github.com/MekayelAnik/ispyagentdvr-docker
