### ISSUE TITLE
FFmpeg 6 update on Docker

### ISSUE THREAD

**Issue by alexbn71** [doitandbedone/ispyagentdvr-docker#643]
..it doesn't work. I see the message "Agent DVR: Installing FFmpeg 6" but nothing happen. Can we do this install manually inside the container?

Thanks
Alex

**Comment by ispysoftware** [comment]
Hey Alex, not sure what's going on with this docker version but this one is confirmed working on latest version
https://hub.docker.com/r/mekayelanik/ispyagentdvr

**Comment by alexbn71** [comment]
I've already tried it but I preferred to stay on the more historic one. I see that in the new versions ffmpeg v5 is still installed inside the container... maybe it would be enough to redo the container with version 6 inside?

**Comment by ispysoftware** [comment]
yes should be ok, i need to make some changes to the docker file, something like removing the ffmpeg5 build stuff and replace it with

RUN echo "Downloading ffmpeg" && \
    wget -c "https://ispyrtcdata.blob.core.windows.net/downloads/ffmpeg6-linuxx64.tar.xz" -O ffmpeg.zip; \
    unzip ffmpeg.zip -d /agent/ffmpeg6 && \
    rm ffmpeg.zip

RUN tar -xvf /agent/ffmpeg6/ffmpeg.tar.xz --strip-components=1 -C "/agent/ffmpeg6"

... but haven't had a proper chance to test it yet
