### ISSUE TITLE
Opendrive doesn't work

### ISSUE THREAD

**Issue by alexbn71** [doitandbedone/ispyagentdvr-docker#646]
![image](https://github.com/doitandbedone/ispyagentdvr-docker/assets/20998190/0936a454-0702-4c80-99eb-29c8a4221018)

<html>
<body>

15:49:44 | Upload: Cloud provider not configured at CoreLogic.Cloud.CloudGateway.Upload(Int32 otid, Int32 oid, String srcPath, String lc, Boolean& success)
-- | --

</body>
</html>

Thanks Alex

**Comment by ispysoftware** [comment]
you need to select open drive on the cloud settings of the device as well
