### ISSUE TITLE
Actions: {MSG} is empty on "Alert"?

### ISSUE THREAD

**Issue by alexbn71** [doitandbedone/ispyagentdvr-docker#647]
Hi,

I noticed that {MSG} variable is set correctly to the text "Manual Alert" when the trigger is "Manual Alert"... but if the action trigger is "Alert" the {MSG} variable is an empty string. Is it normal?

Thanks
Alex

**Comment by ispysoftware** [comment]
well if it's a  normal alert then it's just an alert but sure i can add "alert" to the msg..

**Comment by alexbn71** [comment]
> well if it's a normal alert then it's just an alert but sure i can add "alert" to the msg..

It worked fine in the past

![image](https://github.com/doitandbedone/ispyagentdvr-docker/assets/20998190/0075dc80-e2f5-4448-9926-d6913fa33e23)
