### ISSUE TITLE
Timezone selection not working

### ISSUE THREAD

**Issue by stefangries** [doitandbedone/ispyagentdvr-docker#66]
Usually, when selecting a timezone for a docker container, it is enough to set the TZ environment variable. This does not work for this docker image. To be able to do this, the tzdata package should be added to the image as described here:

https://github.com/phusion/baseimage-docker/issues/513#issuecomment-426635955

```
RUN apt-get update && apt-get install -y tzdata
ENV TZ "America/New_York"
```

**Comment by ispysoftware** [comment]
@doitandbedone could you take a look at this?

**Comment by doitandbedone** [comment]
Sure thing. Should have some time tonight.

**Comment by doitandbedone** [comment]
Change has been implemented. Closing.
