### ISSUE TITLE
OpenAI issue 

### ISSUE THREAD

**Issue by alexbn71** [doitandbedone/ispyagentdvr-docker#677]
I get "Invalid content type. image_url is only supported by certain models." in "AI Scene Recognition"

![image](https://github.com/doitandbedone/ispyagentdvr-docker/assets/20998190/6b233b5c-84d6-4ba0-9def-2823b7ac830d)

![image](https://github.com/doitandbedone/ispyagentdvr-docker/assets/20998190/8ed04649-f433-4bad-bcc4-0f2ba76e1d5e)

**Comment by ispysoftware** [comment]
I think you needed to revert the model name?
