### ISSUE TITLE
{MSG} parameter in "AI: Scene Recognised"

### ISSUE THREAD

**Issue by alexbn71** [doitandbedone/ispyagentdvr-docker#678]
The {MSG} variable is empty... can I suggest to set it to "With tag" field value?

![image](https://github.com/doitandbedone/ispyagentdvr-docker/assets/20998190/70c8e0b7-ab81-4f59-9afb-45fc2ccd3cae)

**Comment by ispysoftware** [comment]
It should be coming through in {AI} but i'll add it to {MSG} as well.
