### ISSUE TITLE
ispy-agent-dvr (truenas / truecharts) - Stuck on deployment

### ISSUE THREAD

**Issue by cv9600** [doitandbedone/ispyagentdvr-docker#694]
Name: ispy-agent-dvr
App Version: 5.3.4.0
Chart Version 9.9.5 
Version: TrueNAS-SCALE-23.10.2

*Bug*
Upgraded from app/chart 5.1.x.x_x.x.x to 5.3.4.0_9.9.3.  After upgrade it started app and would start/deploy, then stop, then start/deploy again, as if to be in a loop.

I did roll back to the 5.1.x.x_x.x.x and it ran fine.   I then tried to install 5.3.4.0_9.9.3 again to see if it had the same issue and it did.  I did this multiple times to see if this just a fluke and would clear up, but it did not. 

I also deleted the app ispy-agent-dvr completely and then did a new installed of ispy-agent-dvr from scratch on TrueNAS-SCALE-23.10.2.  I get the same issue, even after deleting and reinstalling app completely.

**Steps To Reproduce**

1. Go to apps on left side menu of TrueNAS Scale.
2. Right side window that shows "ispy-agent-dvr" select upgrade/update.
3. After TrueNAS Scale updates it you can look on right side window and notice it is stuck at deploy in status.

*I did try to see if I could get to the webgui of ispy-agent-dvr even though it says deploying.  obviously I was not able to do so. Just wanted to make sure the app was not miss displaying deploying in status.  It was not.

**Expected behavior**
1. Go to apps on left side menu of TrueNAS Scale.
2. Right side window that shows "ispy-agent-dvr" select upgrade/update.
3. After TrueNAS Scale updates it you can look on right side window and notice it starts/deploys and then says running in status.
4. Open up WebGUI of ispy-agent-dvr.  See ispy-agent-dvr dashboard.

**Reproduction rate**
Happens 100% after install of ispy-agent-dvr app App Version: 5.3.4.0 - Chart Version 9.9.5

**Screenshots**
Here is the info on the app -
![2024-03-27_12-58_1](https://github.com/doitandbedone/ispyagentdvr-docker/assets/108543739/02693eeb-72bb-46d4-944c-28a8a7f19bcc)

The following is an example of the status stuck at deploy -
![2024-03-27_12-58](https://github.com/doitandbedone/ispyagentdvr-docker/assets/108543739/dad2a312-aa7c-4509-93b6-978ab70d585e)

**Host System Information (where ispy agent is running/hosted):**
 - OS: TrueNAS-SCALE-23.10.2

**Client System Information (device accessing the web portal, if applicable):**
 - OS: Linux Mint 21.3 x86_64
 - Browser: Firefox / Brave / Vivaldi
 - Browser Version: 124.0.1  /  1.64.109 Chromium: 123.0.6312.58 / 6.6.3271.53

**Comment by cv9600** [comment]
Name: ispy-agent-dvr
App Version: 5.3.4.0
Chart Version 9.9.5
Version: TrueNAS-SCALE-23.10.2

I have upgraded to  chart version 9.9.6 and then now 9.9.7 and not change... still stuck on deploying.

Deleted 9.9.7 then re-installed it.  Still deploying.

Please advise.

**Comment by ispysoftware** [comment]
latest version is 5350 - you'd need to get some logs/ debug output from it

**Comment by cv9600** [comment]
Name: ispy-agent-dvr
App Version: 5.3.5.0
Chart Version 9.9.8
Version: TrueNAS-SCALE-23.10.2

Okay, good news.  It looks like after upgrading to 5350 I am able to run as show below,

![2024-03-31_17-10_1](https://github.com/doitandbedone/ispyagentdvr-docker/assets/108543739/ff81b53b-eabe-4258-ba7d-8c1830fa75c2)

![2024-03-31_18-30](https://github.com/doitandbedone/ispyagentdvr-docker/assets/108543739/1068b887-66d7-4a90-8f38-e0b51975e848)

Thanks you for both your help.

**Comment by ispysoftware** [comment]
great thanks for the feedback
