### ISSUE TITLE
Install stuck on "Agent DVR: Installing FFmpeg 6" on MacOS

### ISSUE THREAD

**Issue by guru-florida** [doitandbedone/ispyagentdvr-docker#713]
**Affected Version**
v5.4.0.0

Installed the app on MacOS. Went to WebUI after install. Stuck at a screen saying "Agent DVR: Installing FFmpeg 6". Logs are empty too. Waited hours and tried a second install with the same result.

**Steps To Reproduce**
- Install on OSX using suggested homebrew command (from docs)
        bash <(curl -s "https://raw.githubusercontent.com/ispysoftware/agent-install-scripts/main/v2/install.sh")
- wait for homebrew to install dependencies and finally Agent DVR
- Open WebUI on port 8090 to complete install...but get stuck on the Installing ffmpeg part (waited hours)

**Expected behavior**
The GUI interface to load.

**Reproduction rate**
100% (tried 3 times)

**Host System Information (where ispy agent is running/hosted):**
MacOS Sonoma 14.4.1

**Client System Information (device accessing the web portal, if applicable):**
 - OS: MacOS Sonoma 14.4.1
 - Chrome Browser - Version 123.0.6312.123 (Official Build) (x86_64)

**Install output at command prompt**
```
Starting AgentDVR
Log start
Agent (v5.4.1.0)
Starting...
Detected: OSX64
Creating temp path for opencv in /var/folders/dc/g1wjrvz51rxgg8v8kb55wjj80000gn/T/
Get com port list
Conf: Check /Users/colinfmackenzie/src/nokia/agent-dvr/AgentDVR/Media/WebServerRoot/Media/
Using WorkStation GC
StartUp: Inbuilt SOAP auth unavailable (using alternate)
Using Original WebRTC library
Computer Name: M-C02CD0WCMD6M
Init FFmpeg
/opt/homebrew/Cellar/ffmpeg/ not found
Checking in /usr/local/Cellar/ffmpeg/
/usr/local/homebrew/Cellar/ffmpeg/ not found
Installing FFmpeg6
Init: NDI
Init SDL
Database
Preloading Images
Init: MQTT not configured or enabled
GetObjects: Loaded 0 cameras and 0 mics from /Users/colinfmackenzie/src/nokia/agent-dvr/AgentDVR/Media/XML/objects.xml
LocalServerPort: Using default port (8090)
Access locally at http://localhost:8090/
LogLevel: Info
Running at http://localhost:8090/
/opt/homebrew/Cellar/ffmpeg/ not found
Checking in /usr/local/Cellar/ffmpeg/
/usr/local/homebrew/Cellar/ffmpeg/ not found
Listen: Accepting http connections at http://*:8090/
AddressListIPv4: nodename nor servname provided, or not known    at System.Net.Dns.GetHostEntryOrAddressesCore(String , Boolean , AddressFamily , ValueStopwatch )
   at System.Net.Dns.GetHostEntryCore(String , AddressFamily , ValueStopwatch )
   at System.Net.Dns.GetHostEntry(String , AddressFamily )
   at CoreLogic.Statics.get_AddressListIPv4()
Init: ZeroConf Service Started
AddressListIPv4: nodename nor servname provided, or not known    at System.Net.Dns.GetHostEntryOrAddressesCore(String , Boolean , AddressFamily , ValueStopwatch )
   at System.Net.Dns.GetHostAddressesCore(String , AddressFamily , ValueStopwatch )
   at System.Net.Dns.GetHostAddresses(String , AddressFamily )
   at System.Net.Dns.GetHostAddresses(String )
   at CoreLogic.Statics.get_AddressListIPv4()
PingCompleted: found 127.0.0.1
```

**Comment by guru-florida** [comment]
It may possibly be that ffmpeg 7 is requested and installed by homebrew but perhaps AgentDVR is expecting ffmpeg6?

**During the hombrew dependencies install**
```
Warning: ffmpeg 7.0 is already installed and up-to-date.
To reinstall 7.0, run:
  brew reinstall ffmpeg
```

**From the AgentDVR startup log**
```
Init FFmpeg
/opt/homebrew/Cellar/ffmpeg/ not found
Checking in /usr/local/Cellar/ffmpeg/
/usr/local/homebrew/Cellar/ffmpeg/ not found
Installing FFmpeg6
```

**Comment by ispysoftware** [comment]
yes it looks like homebrew have updated to ffmpeg 7 - Agent needs v6 
you could try brew install ffmpeg@6 - i'm not sure if that exists, if it doesn't we'll need to link it to a specific commit - let me know

**Comment by guru-florida** [comment]
Yes, I was able to install  ffmpeg v6 using:
```
brew install ffmpeg@6
```

Then I had to go into _/usr/local/Cellar/ffmpeg_ and install a soft link since the brew install of ffmpeg@6 doesn't add the package to the normal ffmpeg dir.
```
cd /usr/local/Cellar/ffmpeg
ln -s ../ffmpeg@6/6.1.1 6
```

**Comment by ispysoftware** [comment]
Setup script has been updated
