### ISSUE TITLE
high CPU usage

### ISSUE THREAD

**Issue by TungstenE2** [doitandbedone/ispyagentdvr-docker#74]
Hi,

why is docker version on Synology using so much CPU, even while all cams are disabled?

![grafik](https://user-images.githubusercontent.com/39955685/95842355-be821500-0d46-11eb-8e5c-ab53124a642f.png)

**Comment by ispysoftware** [comment]
Does it stay like that? That's only been up for 3 minutes. It might be running network discovery or storage management. Can you check the logs?

**Comment by TungstenE2** [comment]
yes, stays up like this, otherwise I would not have opened a ticket.

![grafik](https://user-images.githubusercontent.com/39955685/95883322-15094680-0d7b-11eb-89db-728158271805.png)

**Comment by ispysoftware** [comment]
5 cams streaming? That'll be it then

**Comment by TungstenE2** [comment]
this morning I had to restart the container as the browser could not connect, but CPU was still at 28.7%. uptime 21hrs.
![grafik](https://user-images.githubusercontent.com/39955685/95953689-74f30200-0dfa-11eb-9b52-a661188384f7.png)
![grafik](https://user-images.githubusercontent.com/39955685/95953755-93f19400-0dfa-11eb-8175-c7a6658b2f7b.png)

After restart and disabeling all 5 cams the CPU was about 3% and about 2% with no active browser window.
But still this is more than my other dockers usage. Please check for optimizations.

**Comment by ispysoftware** [comment]
i'm not sure what's causing that - on my PC, Mac and Linux boxes it sits at 0% cpu with all cameras disconnected but none of those are docker containers. Maybe docker is downloading updates or doing something else in the background? I don't know much about docker personally, maybe @doitandbedone  has some insight?

**Comment by TungstenE2** [comment]
If you are not familiar with docker, why are you answering to all issues here in the docker version?

**Comment by doitandbedone** [comment]
Docker will definitely will end up using more resources than a native.
After all, the container will be consuming some resources to run. The image
in this case is only running agent on lighter version of linux with minimal
dependencies. 2~3% doesn't sound too bad, but will look at it and see what
could be possibly using CPU while idle.

In the meantime you can try the optional lite version and see if it cuts
down on resources, it should use less disk space however.

**Comment by doitandbedone** [comment]
In my case it pretty much staying less than 2% but does bounce around between 1~3% CPU usage when idle. There are 50 processes 40+ processes started and running however.
<img width="1329" alt="Screen Shot 2020-10-14 at 12 58 04 AM" src="https://user-images.githubusercontent.com/61026996/95960541-b662bd80-0db8-11eb-954f-c68149d718a1.png">

**Comment by doitandbedone** [comment]
From what I can see it's all coming from dotnet on Agent.dll. Perhaps the coturn and discovery threads started. Can't get much info from the thread tree however.

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  337 62.3 21762736 15330984 pts/0 Ssl+ Oct10 19438:40 dotnet /agent/Agent.dll
root     14808  0.0  0.0  21772  3876 pts/1    Ss   01:02   0:00 bash
root     14843  0.0  0.0  37664  3416 pts/1    R+   01:06   0:00 ps -aux
dotnet───48*[{dotnet}]
```

**Comment by ispysoftware** [comment]
> If you are not familiar with docker, why are you answering to all issues here in the docker version?

mainly because the questions you've been asking aren't specific to docker but no probs, i'll just ignore any future questions from you.

**Comment by TungstenE2** [comment]
thx @doitandbedone, so it is right to assume that each active stream adds about 10% CPU usage?

**Comment by doitandbedone** [comment]
The usage would be relative to your setup. It varies between your server
hardware and streaming settings per camera. You could lower settings/fps on
cameras if your system is a bit low on resources.

**Comment by stripeyhorse** [comment]
![image](https://user-images.githubusercontent.com/10705906/97975458-45de1800-1e1d-11eb-9050-8a765bf2916f.png)

Unraid with 3 cameras here.. Not overly high really..

**Comment by doitandbedone** [comment]
Usage seems to be normal and relative to demand on the system. Closing issue.
