### ISSUE TITLE
restart container after backup upload

### ISSUE THREAD

**Issue by TungstenE2** [doitandbedone/ispyagentdvr-docker#75]
Hi,

why do I need to restart the container after uploading backup xml from desktop version?

thx

**Comment by ispysoftware** [comment]
You'll need to check the logs under the server menu

**Comment by TungstenE2** [comment]
seems like the log only starts after last docker reboot

**Comment by TungstenE2** [comment]
tried the restore twice, both times it crashed and I needed to reboot. but cams were working afterwards

**Comment by ispysoftware** [comment]
Can you share the backup xml file?

**Comment by ispysoftware** [comment]
also is the docker version the same version as the desktop version? Is the desktop version windows or OSX or linux?

**Comment by TungstenE2** [comment]
yes, same version. Windows.

I can share the xml later, but need to remove credentials first.

**Comment by doitandbedone** [comment]
@TungstenE2 is there an update on the issue? If you haven't provided the asked info, please do so to be able to have a better understanding. Thanks!

**Comment by doitandbedone** [comment]
@TungstenE2 is there an update on the issue? If you haven't provided the asked info, please do so to be able to have a better understanding. Thanks!

**Comment by doitandbedone** [comment]
@TungstenE2 Closing issue, feel free to reopen if you have any further issues.
