### ISSUE TITLE
feature request: enable and disable all cams

### ISSUE THREAD

**Issue by TungstenE2** [doitandbedone/ispyagentdvr-docker#76]
Like in iSpy please provide option to enable/disable all cams at once

**Comment by TungstenE2** [comment]
this is not very user friendly. at least 3 clicks to get there. would be cool to have the option to add user specific command buttons to the footer bar.

![grafik](https://user-images.githubusercontent.com/39955685/95883725-8c3eda80-0d7b-11eb-9161-7d0504f2dc02.png)

**Comment by doitandbedone** [comment]
Closing as the feature is already in place.

**Comment by TungstenE2** [comment]
@doitandbedone why closing? feature as requested is not in place.

**Comment by ispysoftware** [comment]
i'll think about how to make this easier to use, like a shortcut key or something but having a block of buttons at the bottom is a non-starter - the screen space is best used by the cameras.

**Comment by TungstenE2** [comment]
agreed
