### ISSUE TITLE
mic permission

### ISSUE THREAD

**Issue by TungstenE2** [doitandbedone/ispyagentdvr-docker#77]
Opening URL for local version Firefox is asking for mic permission, while docker version does not. Why not?

**Comment by ispysoftware** [comment]
it'll only ask for permission if it detects that it needs it and you haven't clicked to remember the setting when visiting the site and an audio device is available to get permission for. Possibly the turn server stuff in the docker version is negating the need for mic permissions. You can check the browser developer logs for error messages that might be logged when trying to get mic permissions - if there's a problem Agent will log an error and proceed anyway.

**Comment by TungstenE2** [comment]
to be honest the logs,json is a bit hard to read, being a 1 liner...

I would have expected both applications (windows and docker) acting the same way.

**Comment by ispysoftware** [comment]
i was talking about the dev tools in the web browser not the agent log file

**Comment by doitandbedone** [comment]
Any updates on this issue? @ispysoftware did you need more info?

**Comment by ispysoftware** [comment]
I'm guessing its because one is using localhost and the other is using an ip address. That gives 2 different sets of default permissions. It's not a code issue regardless
