### ISSUE TITLE
Dual stream from camera

### ISSUE THREAD

**Issue by DeadEnded** [doitandbedone/ispyagentdvr-docker#8]
Quick question:

Is it possible to set the viewing stream in Agent to use a low def secondary stream from a camera, while having the recordings use the high def primary stream?

Thanks,
DeadEnd

**Comment by doitandbedone** [comment]
That would be a question to the actual developer, maybe @ispysoftware can answer this.

**Comment by ispysoftware** [comment]
Hello no not at the moment, definitely something i can add though. Thanks for the suggestion.

**Comment by DeadEnded** [comment]
You're most welcome.
I think it can be / is a popular setup (at least in my small circle).
It reduces CPU utilization but still allows for high def recordings (assuming there is a way to do passthrough recording / direct to drive - whatever they want to call it where the stream is saved without decoding/re-encoding).

People do this to do detentions on a low def stream so that CPU isn't hammered - but then save recordings triggered by the detection from a high def stream.  really cuts down on the load, and as long as your low def stream is clear enough no real lose of functionality (missed triggers, etc.).

Thanks again!
DeadEnd

**Comment by stripeyhorse** [comment]
My use case would be kinda the same 24/7 recording at low res , but when movement is detected etc record at the full stream.

i want the detection done on the high def stream thou as my server can handle it for my 4 cameras easily.

**Comment by ispysoftware** [comment]
you can do this by just adding the camera twice with different settings

**Comment by ispysoftware** [comment]
@DeadEnded will be in next update

**Comment by DeadEnded** [comment]
Awesome!  I'll try and test it out once released.
Thanks!

**Comment by DeadEnded** [comment]
Just got the container back up and running (and found a possible bug on ONVIF with h265 - created issue) and since its been awhile since I used it I can't seem to find the setting I am looking for...

For recording, I see that you can set it up for on detection or on alarm, but is there a way to set it up so it does continuous recording?  I suppose I could set the limits and then click record on the live stream - but if I wanted to setup the cameras to do 24/7 recording what is the "correct" way?  Maybe I just missed it...

**Comment by ispysoftware** [comment]
set a schedule entry to start record without a stop time and set apply
schedule on startup in settings.

**Comment by ispysoftware** [comment]
@DeadEnded  this is in the latest update

**Comment by doitandbedone** [comment]
Thanks! New version, 3.0.3.0 it's building, should be available in a few
mins.

**Comment by ispysoftware** [comment]
@doitandbedone is it working ok? had a report about GPU decode breaking streams

**Comment by DeadEnded** [comment]
I see the dual stream (live and record URLs).
I did a short record from the GUI (start, wait, step) and it appeared to record the correct "record" stream.
I then took a snapshot, and it appears the snapshot pulled from the "live" stream.
What are your thoughts about where the snapshot should come from?
I would prefer it from the "record" stream, but you could also add a field to select the stream as well.

On the schedule use for 24/7 recording... I setup a trigger on every day at 12am to start recording.
If I understand this correctly though it will only trigger at 12am... so if I setup a camera now it won't start recording until midnight?  What happens then if I restart the program... it won't record until the trigger hits at midnight again?  If I am understanding this correctly, then I will need to manually trigger the recordings initially?  Just trying to understand how to get the result I am trying to achieve.

Thanks!
DeadEnd

**Comment by ispysoftware** [comment]
Can't snapshot the high res stream without decoding it unfortunately. You can snapshot the recording though whilst playing it back.

Agent will work out the state that it should be in according to the schedule. If there's no stop recording entry then it'll start recording.

**Comment by DeadEnded** [comment]
Thanks for the explanation of the snapshot - working as intended is fine by me - just wanted to check.

I have the schedule setup - I even turned off and on the camera and it hasn't started:
![image](https://user-images.githubusercontent.com/45110141/102547789-b7012400-4087-11eb-8e7f-ffe7a8cbbf76.png)

The only thing I haven't done yet is restart AgentDVR.
I will try that next ( i have the apply schedule at startup checked).
Just trying to understand how it works... would there every be a plan to just add a continuous record flag as an option?
On that same note... with the schedule running - can you still also trigger a motion or alert recording?
So you could do 24/7 recording and then additionally trigger a second recording on motion for short clips?
Just wondering on how it works - seems like that might work, but wasn't sure if the second recording would conflict or fail because a recording is already in process.

Thanks again!
DeadEnd

**Comment by ispysoftware** [comment]
Check the main schedule enable switch is on on the general tab.
If it's already recording them it won't start recording again. The way to do that would be to add the camera twice with different settings. One for continuous record and the other for motion detected record.
