### ISSUE TITLE
YOLO not working on docker

### ISSUE THREAD

**Issue by stripeyhorse** [doitandbedone/ispyagentdvr-docker#80]
I have this install in Unraid via Docker..

YOLO does not seem to be working.

FULL LOG

` YOLO: YOLO: The type initializer for 'Gdip' threw an exception.
[33m[40mError: YOLO: at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, HandleRef scan0, IntPtr& bitmap)
m.Drawing.Bitmap..ctor(Int32 width, Int32 height, Int32 stride, PixelFormat format, IntPtr scan0)
ogic.AI.Yolo.Process(Mat frame)
[33m[40mError: YOLO: YOLO: Unable to load DLL 'libgdiplus': The specified module could not be found.
[33m[40mError: YOLO: at System.Runtime.InteropServices.FunctionWrapper`1.get_Delegate()
m.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
m.Drawing.SafeNativeMethods.Gdip..cctor()
[31m[40mUnable to load DLL 'libgdiplus': The specified module could not be found.
[33m[40mError: YOLO: YOLO: The type initializer for 'Gdip' threw an exception.
[33m[40mError: YOLO: at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, HandleRef scan0, IntPtr& bitmap)
m.Drawing.Bitmap..ctor(Int32 width, Int32 height, Int32 stride, PixelFormat format, IntPtr scan0)
ogic.AI.Yolo.Process(Mat frame)
[33m[40mError: YOLO: YOLO: Unable to load DLL 'libgdiplus': The specified module could not be found.
[33m[40mError: YOLO: at System.Runtime.InteropServices.FunctionWrapper`1.get_Delegate()
m.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
m.Drawing.SafeNativeMethods.Gdip..cctor()
[31m[40mUnable to load DLL 'libgdiplus': The specified module could not be found.`

**Comment by doitandbedone** [comment]
Is YOLO something you added @stripeyhorse ? I'm afraid I'm not familiar with it. I also use Unraid.
@ispysoftware you familiar with it?

**Comment by ispysoftware** [comment]
Yolo is part of agent. It's used under intelligence options. Looks like the Docker image is missing libgdiplus.

**Comment by stripeyhorse** [comment]
i have no idea how the motion detection works , but this could also be why person detection is not working..

btw. Any plans for Google Coral based acceleration?

**Comment by ispysoftware** [comment]
It's not related to the person detector - that's an opencv haar cascade
implementation. If it's not working well you could try playing with the
settings.
I hadn't heard of Coral, will take a look. It looks like quite a niche
thing right now though.

**Comment by doitandbedone** [comment]
Definitely taking a look into it. The huge downside however, for live
products sometimes is not reliable to use some Google products as they
often offer limited and ephemeral life cycles.

**Comment by stripeyhorse** [comment]
Thanks guys.. @ispysoftware is there a official github for agent DVR? 

btw. I just turned off my VM that was running blue iris since Agent DVR is better in every way.

**Comment by doitandbedone** [comment]
I started the project to make this convinient to people, as I know docker
is now widely used. I haven't changed the 'Unofficial' since it's not a
channel created by ispy, however it is being supported, unofficially, by
ispy.
