### ISSUE TITLE
More flexible encoding options for recordings

### ISSUE THREAD

**Issue by doitandbedone** [doitandbedone/ispyagentdvr-docker#91]
**Is your feature request related to a problem? Please describe.**
I'm trying to combine all timelapses into on, save events still as separate clips and upload them to the cloud as backup. The problem are **webm** files. They are proving to be rather time consuming and are not compatible/eligible for online playback. **mkv** files on the other hand are working as expected.

**Describe the solution you'd like**
Is there a way to change the file formats (extensions)? Seems webm is not widely compatible, specially among cloud backups with players. I noticed timelapses are recorded as webm, some regular videos too (seems non raw option in encoder forces it) and finally mkv, which seems the most compatible and easy to manipulate (seems raw encoder outputs mkv).  I'm hoping to force mkv's for all outputs.

**Describe alternatives you've considered**
N/A

**Additional context**
I'm using ffmpeg to stitch together the different files. The webm files seem to be encoded with the old VP8 and is being forced into VP9 and takes way too long to do so, yet still not compatible. The following formats are compatible:
.mpg, .mod, .mmv, .tod, .wmv, .asf, .avi, .divx, .mov, .m4v, .3gp, .3g2, .mp4, .m2t, .m2ts, .mts, and .mkv
Would it be possible? Also, which one would you recommend in terms of ease, higher compression, lower encoding times and least quality loss?

Thank you!

**Comment by ispysoftware** [comment]
mkv is a container format which will store pretty much any audio/video formats so it's ideal for raw recording
webm is the default for linux/osx/docker as it's free (no licensing issues) and has the best encode performance/ file size 
mp4 is the default encoder for windows. I don't think the ffmpeg build for linux/ docker includes the mp4 codec but i'll take a look at it

**Comment by ispysoftware** [comment]
there are some instructions here for nvidia hardware encoding
https://www.tal.org/tutorials/ffmpeg_nvidia_encode

**Comment by doitandbedone** [comment]
Been at it the WHOLE day and no luck, some dependencies missing and the
official nvidia website is outdated, this has something different,
definitely trying it thanks!

**Comment by doitandbedone** [comment]
Still going at it, however, is it possible to use other encoders such as H.264?

**Comment by ispysoftware** [comment]
yes, it's possible, just need to find an ffmpeg build with libx264 or
equivalent enabled. Most of them have it disabled due to licensing issues.

**Comment by doitandbedone** [comment]
As far as ffmpeg goes, what libraries are necessary for Agent to work? If you don't mind me asking, trying to see if I can build a GPU enabled image for hardware acceleration, just get a blank screen for cameras, guessing I'm missing a few things the recommended ffmpeg repo already has.

**Comment by ispysoftware** [comment]
First step is being able to choose mp4 in the ui. I'll look into it today

**Comment by ispysoftware** [comment]
you'll need to check the log under the server menu

**Comment by ispysoftware** [comment]
should be able to use MP4 in all platforms now (it's the default for new installs)

**Comment by doitandbedone** [comment]
Perfect, thank you! I'll integrate the updates.
